PnX-SI/GeoNature

- docs/installation.rst
Installer le module cgi qui ne l'est plus par défaut (pour que mapserver puisse fonctionner)
> Configuration Apache 2.4

- docs/install_all/2016-12-exemple-deploiement-pnr.rst
Ajout d'une condition dans la requête pour éviter la création de doublons si la table bib_noms est déjà peuplée
> Paufinage SQL import bib_noms

- docs/development.rst
- docs/index.rst
- docs/install-mtes.rst
- docs/installation.rst
- docs/installation_developer.rst
- Use same titles formats in all RST files
- Fix some minor typos
- Fix some DEV DOC problems after MERGE
- Add user manual to DOC index
> Fix doc titles and typos

- frontend/src/app/metadataModule/datasets/dataset-form.component.html
- frontend/src/app/metadataModule/datasets/dataset-form.component.ts
Correction d'une inversion dans les checkboxes des domaines terrestre et marin du formulaire des JDD. Edition inversée dans les champs booléen concernés côté BDD.
> [Métadonnées] Inversion domaines terrestre/marin dans JDD

- frontend/src/app/app.component.ts
- frontend/src/app/components/nav-home/nav-home.component.ts
Toute p'tite PR pour intégrer translate dans le app.component. Ca permet de l'avoir (le translate) sur la page de log et de corriger le message "LoginError" pas beau.
> Correction translate

- backend/geonature/core/users/routes.py
- frontend/src/app/app.module.ts
- frontend/src/app/routing/app-routing.module.ts.sample
- frontend/src/app/routing/routes-guards.service.ts
Le controle des routes du frontend mélangeait les paramètres ENABLE_SIGN_UP et ENABLE_USER_MANAGEMENT. Ce qui faisait qu'il était impossible d'avoir les fonctionnalité quand ENABLE_SIGN_UP seul était activé
> Controle des routes différentié en fonction des paramètres de ACCOUNT_MANAGEMENT

- frontend/src/app/GN2CommonModule/form/geometry-form/geometry-form.component.html
- frontend/src/app/GN2CommonModule/form/geometry-form/geometry-form.component.ts
Modification pour initialiser le composant geometryform dans le cas ou le parentFormControl possède déjà une valeur à l'initialisation du composant.
> geometry form initial value

- frontend/src/app/GN2CommonModule/map/geojson/geojson.component.ts
- frontend/src/app/GN2CommonModule/map/map.service.ts
Modification permettant de prendre en compte le cas où l'input style de l'element pnx-geojson est renseigné
> pnx-geojson input style

- frontend/src/app/GN2CommonModule/map/geojson/geojson.component.ts
Dans le composant pnx-geojson, modification pour pouvoir changer le style du geojson quand l'input "style" change
> geojson gerer les changements de style

- docs/CHANGELOG.rst
- frontend/src/app/services/module.service.ts
Correction pour ne pas afficher les modules pour lesquels le paramètre active_frontend est False
> Displayed modules

- frontend/src/app/GN2CommonModule/map/map.component.html
- frontend/src/app/GN2CommonModule/map/map.component.scss
Pour permettre d'adapter le height de la carte si le height d'un contenant parent est modifié. Plus simplement faire que `<pnx-map height="100%">` fonctionne.
> Modif de l'attribution du height du map container

- frontend/src/app/GN2CommonModule/map/map.component.ts
Ajout de la possibilité d'afficher une couche WMS dans le composent map.component.
```
Exemple de config
BASEMAP = [
{"name" = "OpenStreetMap", "layer" = "//{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png", "attribution" = "&copy OpenStreetMap"},
{"name"= "OpenTopoMap", "layer" = "//a.tile.opentopomap.org/{z}/{x}/{y}.png", "attribution" = "© OpenTopoMap"},
{"name" = "OSM Naturaliste","url"="https://osm.geo2france.fr/mapproxy/service?SERVICE=WMS","layers" = "naturaliste", attribution="© Geo2France et Picardie Nature. Données OpenStreetMap"},
]
```
Ca peut être amélioré en permettant la définition d'autres paramètres WMS (seul _layers_ peut être défini ici), mais je ne suis pas assez à l'aise sur TypeScript pour ça ;-)
> Add WMS support

- backend/geonature/utils/gn_module_import.py
Add use of Nvm to load correct Node version for GeoNature before installing JS dependencies with Npm.
Fix #926.
> Fix install_gn_module: use Nvm when installing JS dependencies

- backend/geonature/utils/config_schema.py
- config/default_config.toml.example
- frontend/src/app/components/nav-home/nav-home.component.html
- frontend/src/app/components/nav-home/nav-home.component.scss
- frontend/src/conf/names_variables.scss
- frontend/src/styles.scss
Proposition d'une petite PR permettant de :
- modifier la couleur du menu haut de l'app via les variables `$navbar-color` et `$navbar-text-button-color` à spécifier dans le fichier custom/custom.scss.
- rendre paramétrable (geonature_config.toml) le nom du fichier de l'image de la structure déposé dans le dossier custom/images
+ Modification des icons servant de bouton d'action en buton.
> Paramétrage de la nav-home

- frontend/src/app/GN2CommonModule/map/marker/marker.component.ts
Corrige le fait de pouvoir passer au Input('coordinates') des coordonnées brutes s'affichant directement sur la carto = rend observable les coordonnées.
> Fix marker.component

- data/core/commons.sql
- data/migrations/2.2.1to2.3.0.sql
gn_commons.v_meta_actions_on_object was causing a problem : ERREUR: syntaxe en entrée invalide pour l'entier : « null ».
This fix this error by getting directly integer from json object, instead of converting integer from text.
> Fix gn_commons.v_meta_actions_on_object

- data/core/synthese.sql
- data/migrations/2.1.2to2.1.3.sql
Ajout d'une condition _NOT ST_TOUCHES()_ dans le trigger de la synthèse pour que les géométries parfaitement frontalières ne soit pas insérées dans _cor_area_synthese_
Le script de mise à jour est rétroactif.
> Ne plus inclure les géometries frontalières

- contrib/occtax/frontend/app/occtax-map-form/form/releve/releve.component.html
- contrib/occtax/frontend/app/occtax-map-form/form/releve/releve.component.ts
- frontend/src/app/GN2CommonModule/form/datasets/datasets.component.ts
- frontend/src/app/GN2CommonModule/form/genericForm.component.ts
Ajoute un EventEmitter au genericFormComponent pour permettre la récupération des données chargées ailleurs.
+ Fix le cas où lors d'une modification de donnée par un observateur de cette données, alors que le JDD de cette données n'est pas associé à l'observateur effectuant la modification, la valeur du select du jdd était vide. Le fix affiche le JDD au format texte, sans permettre sa modification.
> EventEmitter sur genericForm + affichage champ JDD sur occtax

- backend/geonature/core/users/register_post_actions.py
- backend/geonature/core/users/routes.py
- backend/geonature/core/users/templates/email_confirm_user_validation.html
- config/default_config.toml.example
- frontend/src/app/components/sign-up/sign-up.component.ts
Major changes:
- Send an email to GeoNature user after the confirmation of his inscription.
- Add a web service to call from UsersHub in order to execute only GeoNature post inscription confirmation actions (see PnX-SI/UsersHub#115).
- Add post confirmation web service URL to data sended to UsersHub when we create a temporary user.
Minor changes:
- add '+' to authorized characters in email regex of the inscription form
- add in default_config.toml.example the log levels values infos
Close #1035
> Feat inscription: send email to user after confirmation

- frontend/src/app/GN2CommonModule/form/synthese-form/advanced-form/synthese-advanced-form.component.html
- frontend/src/app/GN2CommonModule/form/synthese-form/advanced-form/synthese-advanced-form.component.scss
Hide taxo tree button when SYNTHESE.DISPLAY_TAXON_TREE is false. Isolate
Synthese advanced form inputs in DIV tags with "group-form" CSS class. 
Improve searched taxa display style.
Close #1057.
> Fix frontend/synthese: improve design for advanced-form

- backend/geonature/core/users/register_post_actions.py
- backend/geonature/core/users/templates/email_admin_validate_account.html
- backend/geonature/core/users/templates/email_confirm_user_validation.html
- backend/geonature/core/users/templates/email_login_and_new_pass.html
- backend/geonature/core/users/templates/email_self_validate_account.html
- backend/geonature/utils/config_schema.py
- config/default_config.toml.example
- docs/admin-manual.rst
Add a custom text to email send to user after his sign-up confirmation.
Use a new parameter in config file to define this text.
Normalize all emails template text (add same signature, header...).
Improve "default_config.toml.example" documentation. 
Close #1050.
> Feat tpl/emails: custom text in user sign-up email

- backend/geonature/core/errors/routes.py
- backend/geonature/core/gn_permissions/tools.py
- frontend/src/app/app.module.ts
- frontend/src/app/components/auth/auth.service.ts
- frontend/src/app/services/http.interceptor.ts
Le frontend définie un header Content-Type: application/json
dont le backend se sert pour choisir entre répondre par une 401
(appelle de l’API par le frontend) ou rediriger vers une page de
login (accès directe à l’URI depuis le navigateur - par exemple
vues d’exports).
Close #1193
> backend: réponse 401 ou redirection vers login

- backend/geonature/core/gn_synthese/routes.py
- data/core/commons.sql
- data/core/synthese.sql
- data/migrations/2.6.0to2.6.1.sql
Remplacement de la table gn_synthese.cor_area_taxon peuplé par trigger par la vue gn_synthese.v_area_taxon (#997)
Calcul des taxons uniquement pour une maille donnée par le paramètre occtaxmobile_area_type (gn_commons.t_parameters), avec une maille M5 par défaut.
> remplacement de cor_area_taxon par une vue

- data/core/meta.sql
- data/core/synthese.sql
- data/migrations/2.5.5to2.6.0.sql
* Ajout d'une contrainte d'unicité sur `name_source` dans `gn_synthese.t_sources` > fix: #1215 
* Ajout de contraintes d'unicité sur tous les champs UUID du module `gn_meta` et création d'index unique sur les UUID des cadres d'acquisition et des jeux de données > 
fix: #1239
> fix: Add some missing unique constraints

- data/core/synthese.sql
- data/migrations/2.5.5to2.5.6.sql
- docs/CHANGELOG.rst
Aucune raison de limiter ce champs à 255 charactère dans le standard occTax
> synthese reference biblio type text

- config/default_config.toml.example
Ajout du paramètre DISPLAY_EMAIL_INFO_OBS manquant dans config default
https://github.com/PnX-SI/GeoNature/issues/1066#issuecomment-773969956
> ajout DISPLAY_EMAIL_INFO_OBS dans la config par defaut

- data/core/ref_geo.sql
- data/migrations/2.6.2to2.6.3.sql
* As mentionnend in #1271, migration queries are now in 2.6.2-2.6.3 migration file.
* Add a unique constraint to `type_code` in `bib_areas_types`
* refactor create unique index in ref_geo.sql (removing if not exists, removing schema already defined in search path)
> fix: unique constraints on ref_geo #1270

- docs/admin-manual.rst
- docs/development.rst
- docs/installation-mtes.rst
- docs/installation-standalone.rst
Hi,
I saw that some links in documentation are dead.
I notably replaced old occtax path ``frontend/src/modules/occtax`` and first link to installation-all.rst in installation-standalone.rst
I took the opportunity to replace all references to develop branch by master, but I think maybe it would be better to use github permalinks instead of references to branches (especially for references to lines)
I just clone the repository and didn't launch full installation for now, so I don't really know if e7c27637d8cc994aa9aef4be0cc8a9d9b16f2276 commit is useful (despite I searched in all project for a reference to angular/cli)
Anyway, congratulations for your work ! :)
> Fix dead links in documentation

- contrib/occtax/frontend/app/occtax-form/taxa-list/taxa-list.component.html
Inversion _title_ et _description_ dans la taxa-list pour s'assurer que les boutons d'actions sont toujours visibles (bug d'affichage sur les petits écran et/ou nom trop long).
Le nom du taxon est tronqué si nécessaire (visible en déroulant)
#1299 #1337
> fix : affichage boutons d'actions occtax

- contrib/occtax/frontend/app/occtax-map-list/filter/occtax-map-list-filter.component.ts
- contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.html
- contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
- contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.service.ts
Il y avait un problème d'affichage sur le MapList d'occtax. Le nombre de ligne du tableau est déterminé par la taille de l'écran, mais lors d'une recherche 12 résultats étaient imposé. Si l'écran ne pouvait afficher que 10 lignes il y avait des données qui ne pouvaient être visualisés.
> corrige le nombre de ligne affichée sur releve map-list apres recherche

- data/duplicates_deletion/duplicates.deletion.sql
closes #1324 
Pour tester, aller dans la base et faire tourner le script étape après étape. La suppression n'étant pas obligatoire.
A faire pour plus tard : suppression dans une table source si la table source existe et si elle est présente dans la base.
> sql script for duplicates deletion v1.0

- frontend/src/app/metadataModule/af/af-form.component.html
- frontend/src/app/metadataModule/af/af-form.component.ts
- frontend/src/app/metadataModule/datasets/dataset-form.component.html
- frontend/src/app/metadataModule/services/af-form.service.ts
Pour corriger l'affichage des autres acteurs qui ne s'affichaient pas pour le cadre d'acquisition.
Reprend aussi la gestion des onglets des acteurs selon si c'est une création ou une modification.
Remarque au passage, il est actuellement possible de saisir plusieurs contacts principaux au niveau du cadre d'acquisition. Hors sur le format 1.3.10 ce n'est pas la lecture que j'en fait où la multiplicité n'est pas indiquée en 0..*. En fait la multiplicité n'est pas renseignée...
> [Metadata] - Petites corrections au niveau des forms acteurs

- frontend/src/app/GN2CommonModule/form/synthese-form/dynamycFormConfig.ts
Le filtre avancé "Type d'information géographique" ne fonctionnait pas avec la web app.
Quid de renommer ce fichier  dynamyc -> dynamic  par la même occasion ?
> filtre avancé "type d'information géographique"

- frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.html
Correction de l'affichage des valeurs sélectionnées dans le formulaire de recherche avancé de taxon (synthèse et validation)
Ajout fonction : 
* affichage de la liste des taxons sélectionné par rang (selectedTaxonFromRankInput)
* affichage de la valeur group2_inpn
> Display advanced selection form

- backend/geonature/core/gn_synthese/routes.py
Permettre l'utilisation de l'`id_source` sur la route `taxa_distribution` de la synthèse.
Pour le moment il ne peut être utilisé avec `id_dataset` et `id_af`. A discuter dans #1446
Permet aussi de répondre à https://github.com/PnX-SI/gn_module_import/issues/221
Closes #1446
> feat(synthese): id_source in taxa_distribution

- frontend/src/app/GN2CommonModule/form/data-form.service.ts
cf https://github.com/PnX-SI/GeoNature/issues/1438
> avoid redirect and CORS on biblistes route

- frontend/src/app/GN2CommonModule/form/nomenclature/nomenclature.component.html
- frontend/src/app/syntheseModule/taxon-sheet/taxon-sheet.component.ts
FIx deux bug de la 2.9 : 
- mauvaise URL de Taxhub (slash final manquant) sur le fiche profil
- masquage des liste déroulante des ng-select dans un bloc à longueur/largeur fixe (fix en utilisant `appendTo="body"`)
> Fix frontend

- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
- backend/geonature/utils/config_schema.py
- config/default_config.toml.example
Si on veut garder cette option, il faudrait l’implémenter également dans has_instance_permission du modèle Synthese.
Mais je propose plutôt de virer cette option qui est à priori inutile.
Les observateurs textuels permettent de saisir des observateurs n’ayant pas de compte, mais comme ces derniers n’ont pas de compte, ils ne se connectent pas pour voir leur observation, et donc ce filtre est inutile.
> remove CRUVED_SEARCH_WITH_OBSERVER_AS_TXT

- contrib/occtax/frontend/app/occtax-form/releve/releve.component.scss
Link #1701 
Change le CSS de l'auto-complétions à la saisie de l'habitat d'une observation pour afficher la liste de valeurs avec l'intégralité des informations.
Testé sur écrans > = 15''.
> #1701 fix taxhub habitat list display

- backend/geonature/core/gn_synthese/models.py
- backend/geonature/core/gn_synthese/routes.py
- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
- backend/geonature/tests/test_reports.py
- backend/geonature/utils/config_schema.py
- config/default_config.toml.example
- contrib/gn_module_validation/backend/gn_module_validation/blueprint.py
- contrib/gn_module_validation/frontend/app/components/validation-modal-info-obs/validation-modal-info-obs.component.ts
- contrib/gn_module_validation/frontend/app/components/validation-synthese-list/validation-synthese-list.component.html
- contrib/gn_module_validation/frontend/app/components/validation-synthese-list/validation-synthese-list.component.ts
- contrib/gn_module_validation/frontend/app/services/data.service.ts
- frontend/src/app/GN2CommonModule/form/synthese-form/dynamicFormConfig.ts
- frontend/src/app/GN2CommonModule/form/synthese-form/synthese-data.service.ts
- frontend/src/app/shared/alertInfoModule/alert-Info.component.html
- frontend/src/app/shared/alertInfoModule/alert-Info.component.scss
- frontend/src/app/shared/alertInfoModule/alert-Info.component.ts
- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html
- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts
- frontend/src/app/shared/syntheseSharedModule/synthese-shared.module.ts
- frontend/src/app/syntheseModule/synthese.module.ts
_Ref. issue #1750_ 
> Cette contribution a été réalisée selon les besoins de [picardie-nature](http://www.picardie-nature.org/) @jbdesbas 
Cette proposition de PR permet, depuis le module “Synthèse”, de pouvoir signaler une
observation semblant erronée ou suspecte.
Une observation aberrantes / suspecte pourra alors être rapidement rendue visible via un bouton `signaler` et un formulaire afin d'ajouter un commentaire. Les observations signalées sont ensuite mise en évidence dans la liste des occurrences de la VALIDATION et recherchable via un filtre avancé "Est signalé".
Cette fonctionnalité est optionnelle car visible ou non dans les modules `SYNTHESE`, `VALIDATION` ou dans aucun des deux selon les détails fourni dans l'issue 1750.
Les éléments suivants on été modifiés ou rajoutés : 
Tout …
> Ajouter un signalement sur une occurrence pour la validation

- .github/workflows/pytest.yml
- backend/geonature/core/gn_meta/repositories.py
- backend/geonature/core/gn_synthese/models.py
- backend/geonature/core/gn_synthese/routes.py
- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
- backend/geonature/core/ref_geo/routes.py
- backend/geonature/tests/fixtures.py
- backend/geonature/tests/test_synthese.py
- backend/geonature/tests/utils.py
- backend/geonature/utils/config_schema.py
- frontend/src/app/GN2CommonModule/form/areas/areas.component.ts
- frontend/src/app/components/home-content/home-content.component.ts
- frontend/src/app/syntheseModule/synthese-results/synthese-carte/synthese-carte.component.ts
- frontend/src/app/syntheseModule/synthese.component.ts
Cette vue est inutile : elle se contente de joindre d’autres tables, et de demander le calcule de la géométrie en *geojson*. Il n’y a pas d’intérêt à maintenir cette vue, et devoir gérer un deuxième modèle (ainsi que la générécité du filtre générique SyntheseQuery qui découle de ces 2 modèles) alors que ces jointures et le calcule du *geojson* peuvent être fait très simplement avec SQLAlchemy.
Une colonne ``the_geom_4326_geojson`` a été rajouté sur le modèle ``Synthese`` :
```
the_geom_4326_geojson = column_property(func.ST_AsGeoJSON(the_geom_4326), deferred=True)
```
> Suppression de la vue v_synthese_for_web_app

- contrib/occtax/backend/occtax/migrations/22c2851bc387_add_database_default_value.py
- contrib/occtax/backend/occtax/migrations/todo_revision.py.test
- contrib/occtax/backend/occtax/models.py
fix : https://github.com/PnX-SI/gn_mobile_occtax/issues/146#issuecomment-1102985816
> Set default nomenclature value on database side

- backend/geonature/core/gn_synthese/routes.py
- backend/geonature/tests/test_synthese.py
Ajout d'un filtre d'affichage de la bbox sur l'`id_source` en plus de l'`id_dataset` déjà présent.
Permet notamment au module d'import d'afficher les données dans le rapport d'import, mais pourra servir à faire des filtres plus avancés type OccTax + `id_dataset` par exemple.
> feat/synthese: add id_source to bbox

- backend/geonature/utils/config_schema.py
- config/default_config.toml.example
- frontend/src/app/GN2CommonModule/map/map.component.ts
- Ajout d'une condition pour récupérer la `boundingbox` si le `geojson` n'est pas présent dans la réponse de nominatim OpenStreetMap lors de la recherche sur la carte.
- Ajout d'un nouveau paramètre dans la configuration pour pouvoir restreindre cette recherche pour certains pays.
Comme le stipule la [documentation de nominatim OpenStreeMap](https://nominatim.org/release-docs/latest/api/Search/#result-limitation), il est possible de restreindre la recherche à une liste de pays.
Le paramètre proposé permet à l'utilisateur de les fournir sous forme d'une chaîne de caractères respectant le format suivant : 
```toml
[MAPCONFIG]
OSM_RESTRICT_COUNTRY_CODES = "fr,ch,be,sp"
```
Les "pays" à fournir sont en réalité leur code [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). …
> [Carte] Améliorer la robustesse de la recherche OpenStreetMap et restreindre sur certains pays

- backend/geonature/core/command/create_gn_module.py
- backend/geonature/utils/config_schema.py
- backend/geonature/utils/gn_module_import.py
- backend/geonature/utils/module.py
- backend/geonature/utils/schemas.py
Add all module config in the `utils.config.config` variable. 
Module config can now be use without the app_context anywhere in the app
> load module config in main config

- backend/geonature/app.py
- backend/geonature/utils/config.py
- backend/geonature/utils/config_schema.py
- backend/geonature/utils/utilstoml.py
This ensure app.config is identical to imported config object.
In addition, add support for GEONATURE prefixed env variables.
Finally, variables configured from env var or pyfile are not required in toml config file.
> move whole configuration process in config module

- backend/geonature/core/gn_meta/models.py
- backend/geonature/core/gn_meta/routes.py
- backend/geonature/core/ref_geo/routes.py
- backend/geonature/tests/fixtures.py
- backend/geonature/tests/test_gn_meta.py
- backend/geonature/tests/test_ref_geo.py
- backend/geonature/utils/config_schema.py
- config/default_config.toml.example
- frontend/src/app/GN2CommonModule/form/areas/areas.component.ts
- frontend/src/app/GN2CommonModule/form/data-form.service.ts
- frontend/src/app/metadataModule/metadata.component.html
- frontend/src/app/metadataModule/metadata.component.scss
- frontend/src/app/metadataModule/metadata.component.ts
- frontend/src/app/metadataModule/services/metadata-search-form.service.ts
- frontend/src/app/metadataModule/services/metadata.service.ts
- frontend/src/app/syntheseModule/synthese.component.ts
- frontend/src/styles.scss
ref #1768 
> Cette PR a été commandité par le [MNHN](https://www.mnhn.fr/fr).
> Merci à @camillemonchicourt  @bouttier @TheoLechemia pour le support technique et la réactivité
Cette PR  permet de pouvoir filtrer les CA ou les JDD par zonage, notamment par région ou département.
Les développements avaient pour objectif que ce filtre supplémentaire fonctionne comme les autres : tous les JDD des CA retournés.
La PR pourra être mergée après la totale réalisation de ces tâches :
> Filtrer les métadonnées par zonage

- .gitmodules
- backend/requirements-dependencies.in
- backend/requirements-dev.txt
- backend/requirements-submodules.in
Ajout de UsersHub comme submodule tout comme TaxHub. Ceci afin que le Alembic de GeoNature puisse connaître les révisions Alembic de UsersHub.
Actuellement on utilise le paramètre ``VERSION_LOCATIONS`` pour indiquer à GeoNature le chemin vers les révisions de UsersHub, mais cela a pour limitation :
- On ne contrôle pas la version de UsersHub à côté, contrairement à un submodule
- Dans un environnement Docker, on a pas accès aux fichiers de UsersHub, il faut donc l’installer dans l’image de GeoNature, ce que permet cette PR.
Cette PR ajoute UsersHub uniquement aux dépendances de dev, mais pas de prod.
Je pense le rajouter également aux dépendances de prod (ce qui permettra de supprimer le la configuration via ``VERSION_LOCATIONS``) mais il faut pour cela créer un nouveau paquet pypi pour …
> add UsersHub submodule

- backend/geonature/core/gn_meta/mtd/mtd_utils.py
- backend/geonature/core/gn_meta/routes.py
- backend/geonature/templates/acquisition_framework_template_pdf.html
- backend/geonature/templates/dataset_template_pdf.html
- backend/geonature/tests/test_gn_meta.py
- backend/geonature/utils/filemanager.py
- frontend/src/app/GN2CommonModule/form/data-form.service.ts
- frontend/src/app/app.module.ts
- frontend/src/app/metadataModule/af/af-card.component.ts
- frontend/src/app/metadataModule/af/af-form.component.ts
- frontend/src/app/metadataModule/datasets/dataset-card.component.ts
Reprise de #2232 avec :
- les modifs autour de prettier ont été intégré par ailleurs
- correction du content-type pour l’export PDF des cadres d’acquisition
> refactor pdf

- backend/geonature/core/notifications/models.py
- backend/geonature/core/notifications/routes.py
- backend/geonature/core/notifications/utils.py
- backend/geonature/migrations/versions/09a637f06b96_default_notification_rules.py
- backend/geonature/tests/test_notifications.py
- frontend/src/app/components/notification/notification-data.service.ts
- frontend/src/app/components/notification/rules/rules.component.html
- frontend/src/app/components/notification/rules/rules.component.ts
Rules with NULL id_role are used if there are no rules for current user.
> support for default notification rules

- frontend/src/app/GN2CommonModule/form/form.service.ts
Problème à la création de date pour le `dateValidator` du `form.service.ts` (remonté par l'ARB IDF). A l'heure actuelle la comparaison de date dans le formulaire de relevé du module OCCTAX se  base sur des mauvaises dates (déclage d'un mois +1). 
https://github.com/PnX-SI/GeoNature/blob/96c53e51bad9e9be7da3aeb56acf735e955c90ad/frontend/src/app/GN2CommonModule/form/form.service.ts#L15-L16
Proposition de résolution "rapide" en mettant -1 sur le mois pour corriger le problème et obtenir la date correspondante à celle sélectionné dans le "date picker" du formulaire. 
[Refs_ticket]: #2318
> fix: Date comparison problem on form OCCTAX Releve

- backend/geonature/utils/config_schema.py
Dans la validation des options ACCOUNT_MANAGEMENT, le message d'erreur sur les options USERSHUB était incomplet car ne spécifiait pas qu'il fallait les renseigner si ENABLE_USER_MANAGEMENT=True
> fix(api): confusing error msg in Validation

- backend/geonature/migrations/versions/5d65f9c93a32_fix_permissions_view.py
- Return group permission even for group with no users
- Do not duplicate then deduplicate (through union) groups permissions
> Fix v_roles_permissions view (#2344)

- docs/installation-standalone.rst
- install/install_all/install_all.sh
J'ai rencontré quelques erreurs pendant l'installation de GeoNature, dûes à des fichiers PostGIS manquant, notamment :
```
Creating GeoNature database...
Adding default PostGIS extension
ERROR:  could not open extension control file "/usr/share/postgresql/13/extension/postgis.control": No such file or directory
```
puis
```
Creating GeoNature database...
Adding default PostGIS extension
ERROR:  could not access file "$libdir/postgis-3": No such file or directory
```
L'installation des paquets `postgresql-postgis-scripts` et `postgresql-postgis` a corrigé respectivement la première et la deuxième erreur.
> Install postgresql-postgis virtual packages

- backend/Dockerfile
La syntaxe précédente donne une erreur lors du docker run :
```
bin/sh: 1: [: gunicorn,: unexpected operator
```
Je crois que le premier retour à la ligne casse la compréhension de docker.
Testé sur Docker version 20.10.18
> fix(back): docker cmd command syntax

- backend/geonature/utils/command.py
Pour pouvoir exécuter la commande `update_configuration` quand on a des modules packagés qui n'ont pas de frontend (par ex. sous modules gn_modulator)
> patch module without frontend

- contrib/occtax/backend/occtax/migrations/0ff94776a962_t_releves_triggers_optimization.py
Fait en sorte que les triggers ne soient pris en compte que si une des colonnes utilisées dans la fonction du trigger est modifiée dans la table.
> Optimize triggers of t_releves_occtax

- backend/geonature/migrations/data/core/commons.sql
Salut !
Suite à une installation complète de la dernière version (2.11) de GeoNature, taxref est automatiquement mis à jour : https://github.com/PnX-SI/GeoNature/blob/2c300fc4b465b68a08801943b208dcd532fab560/install/03_create_db.sh#L109-L111  mais `gn_commons.t_parameters` n'est pas modifié. Le but de cette PR est de mettre à jour cette table
> fix(db): update taxref_version in commons.sql

- backend/requirements.txt
PR rapide pour mise à jour de certains packages python.
Notamment psycopg2 qui ne build pas en 2.9.3 sur MacOS, mais s'installe bien en 2.9.5.
Upgrade réalisée avec la commande `pip-compile requirements.in`
> feat(backend): bump dependencies versions

- backend/geonature/migrations/versions/e2a94808cf76_add_notifications_object.py
Il n’était pas possible en conséquence de définir une permissions spécifiques pour les notifications. Cependant, été contrôlé les permissions du module ADMIN.
> add NOTIFICATIONS objects related to ADMIN module

- contrib/gn_module_validation/frontend/app/components/validation.component.ts
- frontend/src/app/GN2CommonModule/form/dynamic-form-generator/dynamic-form-generator.component.ts
- frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.html
- frontend/src/app/syntheseModule/synthese.component.ts
La dernière PR ne résolvait pas tout pour #2470
la je me suis assuré que cela fonctionnait pour la valisaiton (pas de filtre par defaut) et pour la synthese (possibilité de mettre des filtres par defaut)
> refix validation filtre avance ref #2470

- backend/geonature/core/gn_synthese/routes.py
- frontend/src/app/syntheseModule/synthese-results/synthese-carte/synthese-carte.component.ts
- frontend/src/app/syntheseModule/synthese.component.ts
Remonte les observations dont la géométries ne se trouve pas dans une maille du référentiel spécifié dans `AREA_AGGREGATION_TYPE`, mais la géométrie est alors `null`.
TODO (frontend) :
- Afficher un message s’il y a une feature avec une géométrie `null` « Attention, {n} observations ne sont pas affichées sur la carte », avec n = taille du tableau de `properties` de la feature
- Gérer le cas où la géométrie est nulle lorsque l’on clique sur un élément dans la liste
Le mécanisme de zoom sur la bounding box a l’air de fonctionner correctement malgré les géom nulles.
https://github.com/PnX-SI/GeoNature/issues/2495
> synthese: left outer join on aggregated areas

- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
> fix(filters): add where on id_role for has_pin

- backend/geonature/core/gn_commons/routes.py
- backend/geonature/core/gn_permissions/tools.py
- backend/geonature/migrations/versions/0630b93bcfe0_add_permissions_inherited_modules_objects.py
- backend/geonature/tests/fixtures.py
- backend/geonature/tests/test_permissions.py
- docs/admin-manual.rst
> feat(permissions): remove modules objects inheritance permissions

- backend/geonature/core/gn_meta/models.py
- backend/geonature/core/gn_meta/routes.py
Récupération des JDD et des DS en regardant le R METADATA plutôt que R GEONATURE.
Pas sûr que ça ne pose pas des soucis, par exemple, si on met un R METADATA à 0 pour interdire l’accès au module méta-données … Cela peut casser notamment les endroits où on utilise le composant `pnx-datasets` en mode pas `CREATE` (en mode `CREATE`, pas de soucis).
Autre utilisation : filtres de la synthèse
> meta: get read perms from METADATA module

- backend/geonature/core/gn_synthese/routes.py
- backend/geonature/migrations/versions/95acee9f0452_add_comment_notification.py
- backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
- backend/geonature/tests/fixtures.py
- backend/geonature/tests/test_notifications.py
- backend/geonature/tests/test_reports.py
Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité Ile De France : ajout d'une notification lorsqu'un commentaire est ajouté sur l'observation d'un utilisateur.
La notification n'est pas envoyé aux utilisateurs commentant une observation qui n'ont pas faite.
**Code de la notification :** VALIDATION-NEW-COMMENT
**Template de mail :**
```html
<p>Bonjour <i>{{ role.nom_complet }}</i> !</p> 
<p>Votre observation de l'espèce : {{ synthese.nom_cite }} du {{ synthese.meta_create_date.strftime('%d-%m-%Y') }} a reçu un commentaire</p>
<p>Vous pouvez y accéder directement <a href="{{ url }}">ici</a></p>
<p><i>Vous recevez cet email automatiquement via le service de notification de GeoNature.</i></p>
```
**Template de notification :** 
```html
Vous avez reçu un nouveau …
```
> feat(api): add notification for comment on obs

- install/03_create_db.sh
psql is executed as postgres user which does not necessarily have permission to read add_pg_extensions.sql file.
> fix create db: pass extensions on stdin

- install/install_all/install_all.sh
Fixes an issue occurring during installation of GeoNature : `envsubst: command not found`.
> fix(install): add gettext linux package for envsubst command

- backend/geonature/core/users/register_post_actions.py
- backend/geonature/core/users/routes.py
- backend/geonature/core/users/templates/account_created.html
- backend/geonature/core/users/templates/email_admin_validate_account.html
- backend/geonature/utils/config_schema.py
- frontend/src/app/modules/login/sign-up/sign-up.component.html
- frontend/src/app/modules/login/sign-up/sign-up.component.ts
> register enhancement

- docs/admin-manual.rst
Révision de la doc admin sur la gestion des droits, suite à la refonte des permissions dans la version 2.13.0 (suppression de l'héritage, nouveaux filtres et définition des permissions disponible)
> Doc admin - Permissions V2

- backend/geonature/core/gn_meta/routes.py
- frontend/src/app/metadataModule/af/af-card.component.html
also opened the file in a new tab and fixed the flashing link when the ca is not closed
-     You need a CA (cadre d'aquisition) with a jdd (jeu de données) and an observation
-     Go to the CA information page in metadata
-     check that the link below the export button doesn't pop in and out
-     go back one page close the ca
-     go check that the link is there and that when you click it works and open on a new page
> fix(CA): added get to the route

- backend/geonature/migrations/versions/f051b88a57fd_permissions_available.py
modified migrantion permission available to add the missing "E" permission used in the route ```/dataset/export_pdf/<id_dataset>```
> fix(permissions): adding missing permission in metadata

- frontend/src/app/GN2CommonModule/map/map.component.ts
Ce qui a été fait :
- Stockage seulement du nom du fond de carte dans le `localStorage` car la couche peut-être retrouvée grâce à la variable `baseControl`
- A la création de la carte : prend la couche contenue dans le `localStorage`. La directive `map.addLayer` n'ajoute pas la couche si elle existe déjà (voir : https://stackoverflow.com/a/33762133) mais la met à jour
- Ajout de conditions pour traiter les erreurs suivantes : `localStorage` vide, nom de la couche introuvable
Attention : cette PR ne traite pas du stockage des `REF_LAYERS` (ZNIEFF, communes etc), car lourd à afficher et n'a pas vocation, selon moi, à apparaitre constamment sur la carte.
Closes #2619
> feat(front): utiliser le localStorage pour stocker le fond cartographique actuel

- backend/geonature/core/gn_synthese/routes.py
Si la PR https://github.com/PnX-SI/GeoNature/pull/2591 n'est pas acceptée, celle-ci garde le comportement précédent (filtre sur les taxons présents en synthèse) mais en appelant la bonne colonne, ajoutée dans Taxhub https://github.com/PnX-SI/TaxHub/releases/tag/1.11.2
> [Synthese] Perf/synthese taxon autocomplete

- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
Closes #2639 
On a modifié les filtres en backend pour corriger le problème de sélection des obs lorsque plusieurs filtres géo sont utilisés : 
- filtre "ET" entre différents types de filtres géo (ex: sélection d'éléments dans ''communes" et "départements")
- filtre "OU" à l'intérieur d'un filtre géo si plusieurs éléments sont sélectionnés (ex: plusieurs communes)
exemple : 
ceci va sélectionner pour la région PACA uniquement les obs faites dans les Hautes-Alpes et le Var.
> fix(backend): multiple geo filters request

- contrib/occtax/frontend/app/occtax-form/map/occtax-map.service.ts
Fix --> Erreur d'affichage lors de l'enchainement de saisie de relevé pour le module occtax . Si la géométrie saisie pour le premier  relevé est un polygon/polyline et que le second relevé est un point ce dernier n'est pas affiché au retour sur le composant map pour le relevé suivant.
Closes #2657
[Refs_ticket]: #2657
> fix(front): OCCTAX displaying last geometry point

- frontend/src/app/GN2CommonModule/form/taxonomy/taxonomy.component.scss
Pour le contexte : https://github.com/PnX-SI/TaxHub/issues/332
La PR de la partie alembic de l'issue est donc liée à TaxHub : https://github.com/PnX-SI/TaxHub/pull/435
Ici la PR concerne uniquement la partie frontend. Permet d'améliorer l'affichage de l'autocomplete lorsqu'il y a de multiples noms vernaculaires (exemples donnés dans l'issue)
> fixes nom_vern search frontend

- frontend/nginx.conf
This is necessary to serve GeoNature without prefix, and still compatible with a prefix.
> add trailing / in nginx alias config

- backend/geonature/core/gn_commons/routes.py
This avoid polymorphic errors when a module is loaded from db but not known as not installed on python side.
The fix is partial as modules are accessed at others places, like from permissions.
> do not retrive disabled modules from db

- frontend/src/app/shared/alertInfoModule/alert-Info.component.ts
On avait retenu que pour que seuls les validateurs puissent supprimer un signalement, on regardait la permission R du module Validation : https://github.com/PnX-SI/GeoNature/pull/1817#issuecomment-1086080755
Mais c'était resté sur la permission V du module Synthèse qui n'existe pas et a été nettoyé lors du passage en 2.13.0.
> fix(synthese) changed required permissions to change report

- backend/geonature/core/gn_synthese/routes.py
- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts
Fix https://github.com/PnX-SI/GeoNature/issues/2507
> fix(synthese) fix pin not working

- backend/geonature/core/gn_commons/routes.py
[occtax mobile] pour pouvoir utiliser un chemin absolu pour l'url de l'apk
#2708
idéalement il faudrait pouvoir ne faire qu'une variable entre url_apk et relative_path_apk (ne garder que url_apk) et traiter selon si elle correspond à une url (commence par https://) ou non (dans ce cas relative à media/mobile)
> fix occtax mobile absolute apk_url ref #2708

- backend/geonature/utils/config_schema.py
Consequently, timezone becomes system local timezone instead of UTC.
En conséquence, les tâches planifiées sont lancé à l’heure local et non UTC, ce qui est sans doute plus naturel pour la plupart des utilisateurs. Il reste possible de spécifier une timezone donnée avec le paramètre `timezone`.
Problème évoqué dans le ticket #2717
> celery: enable_utc=False

- backend/geonature/celery_app.py
- backend/geonature/tasks/__init__.py
Ce fix a été testé en prod au MNHN quelques mois mais n’avait jamais été intégré upstream.
Il ne résous probablement pas tout les soucis soulevé dans #2717 mais peu aider.
> db.session.remove() in celery post run hook

- backend/geonature/core/gn_meta/models.py
- backend/geonature/core/gn_meta/routes.py
- backend/geonature/tests/test_gn_meta.py
- backend/geonature/tests/test_reports.py
Fix le problème de permissions dans Occtax, Occhab et Import sur la liste des JDD (les permissions C du module n'étaient pas prise en compte, mais seulement celles du R sur Métadonnées)
> fix(permission) add the json params to the checked params

- backend/geonature/core/gn_commons/repositories.py
Nous sommes tombés sur un cas, où en tentant d'upload une image portrait directement depuis l'API GN, les thumbnails se retrouvaient "rotatés" de 90°. 
De ce que j'en comprends c'est une metadata EXIF qui dit "orientation = 3" et la librairie PIL, considère que le vrai sens de l'image est 0, il va alors "rotater" l'image de 90° (ou 270°, mais bref).
Je peux essayer de vous fournir des images tests, mais cette metadata semble sauter en cas de transfert du fichier via messagerie ou outil de conversation instantané... 
Le fix que je propose résout bien le soucis, j'ai aussi testé avec des images PNG qui n'ont pas d'EXIF, et pas d'erreur de la part de l'API. Il y a peut être d'autres edge cases auxquels je n'ai pas pensé.
> fix: keep image orientation in thumbnail transformation

- .github/workflows/cypress.yml
- backend/geonature/core/command/main.py
- backend/geonature/utils/command.py
- docs/development.rst
- frontend/src/conf/app.config.ts.sample
- install/05_install_frontend.sh
- install/install_all/install_all.sh
Suppression de la génération du fichier `app.config.ts` (dans le frontend). Lié à l'_issue_  : https://github.com/PnX-SI/GeoNature/issues/2747
> Remove app.config.ts and associated commands 

- frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.html
Prise en compte du paramètre creatableInModule du composant dataset dans les dynamic forms
> Add creatableInModule in datasets component

- backend/geonature/app.py
- backend/geonature/core/gn_permissions/decorators.py
- backend/geonature/core/users/routes.py
- backend/geonature/tests/conftest.py
- backend/geonature/tests/test_gn_commons.py
- backend/geonature/tests/test_gn_meta.py
- backend/geonature/tests/test_notifications.py
- backend/geonature/tests/test_pr_occhab.py
- backend/geonature/tests/test_pr_occtax.py
- backend/geonature/tests/test_reports.py
- backend/geonature/tests/test_synthese.py
- backend/geonature/tests/test_synthese_logs.py
- backend/geonature/tests/test_users.py
- backend/geonature/tests/test_validation.py
- backend/geonature/tests/utils.py
- backend/geonature/utils/config.py
- backend/requirements-dependencies.in
- backend/requirements-dev.txt
- backend/requirements-submodules.in
- frontend/src/app/components/auth/auth.service.ts
- frontend/src/app/routing/auth-guard.service.ts
- frontend/src/app/services/http.interceptor.ts
Abandon du système d'authentification par cookie. Le token d'authentification (JWT) est maintenant passé dans chaque appel à l'API dans le header HTTP "Authorization Bearer". Il est aussi fourni par la route de `login` du sous module d'authentification et stocké dans le localStorage (voir : https://github.com/PnX-SI/UsersHub-authentification-module/pull/64)
Fix : #2161 #490 #2574
> Header auth

- frontend/src/app/components/home-content/home-content.component.ts
fix #2795
**Scope:**
Routing côté frontend
Navigation vers la page d'accueil via le bouton précédent 
**Développement Réalisé:**
A l'initialisation du composant home (ngOnInit), le currentModule du moduleService est mis à null.
Cela permet de s'assurer, peu importe le chemin d'accès, que le module est dans un état correct
> fix: ensure cleaning of current module while initiating home component

- backend/geonature/core/gn_commons/models/base.py
When polymorphic modules are declared in database, but absent from venv, this raise a sqlalchemy polymorphic error. This commit fallback missing polymorphic identities on default "base" identity.
> avoid sqla polymorphic errors

- docs/installation-all.rst
- docs/installation-standalone.rst
The two lines modified were referencing the file `versions-compatibility.rst` removed in commit `632464e`.
Information about versions compatibility between GeoNature, TaxHub, UsersHub and other dependencies can be found in the requirements files : "backend/requirements-*".
> fix(docs): remove two broken references to removed file

- backend/geonature/core/gn_meta/models/aframework.py
- backend/geonature/core/gn_meta/models/datasets.py
- backend/geonature/core/gn_synthese/models.py
- backend/geonature/core/notifications/models.py
- backend/geonature/core/notifications/utils.py
- backend/geonature/tests/test_notifications.py
- backend/geonature/tests/test_sensitivity.py
- backend/geonature/tests/test_synthese.py
- backend/geonature/tests/test_synthese_logs.py
- backend/geonature/tests/test_users.py
- backend/geonature/tests/test_users_menu.py
- contrib/gn_module_occhab/backend/gn_module_occhab/models.py
This PR aims to  : 
This PR is the next step in a SQLA 1.4 upgrade process begun in #2821
> Remove last query classes, 1.3 style SQLA queries and deprecated SQLA objects in the 2.0 version

- frontend/src/app/GN2CommonModule/map/leaflet-draw/leaflet-draw.component.ts
Avant à l'ajout d'une géométrie si on annulait ("cancel") l'ajout de la géométrie alors on revenait sur une map sans aucune layer (la layer d'origine n'était plus présente)
L'ajout de l'event DRAWSTOP permet de gérer ce cas de figure et améliorer l'UX
[Refs_ticket] : #2778 
> feat: add Event DRAWSTOP (improve ux)

- backend/geonature/app.py
- backend/geonature/core/command/create_gn_module.py
- backend/geonature/core/gn_commons/repositories.py
- backend/geonature/core/gn_commons/routes.py
- backend/geonature/core/gn_meta/models/aframework.py
- backend/geonature/core/gn_meta/repositories.py
- backend/geonature/core/gn_meta/routes.py
- backend/geonature/core/gn_permissions/admin.py
- backend/geonature/core/gn_profiles/models.py
- backend/geonature/core/gn_synthese/models.py
- backend/geonature/core/gn_synthese/utils/blurring.py
- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
- backend/geonature/core/notifications/routes.py
- backend/geonature/core/users/register_post_actions.py
- backend/geonature/migrations/versions/0630b93bcfe0_add_permissions_inherited_modules_objects.py
- backend/geonature/migrations/versions/36d0bd313a47_add_notification_schema_tables_and_data.py
- backend/geonature/tests/test_commands.py
- backend/geonature/tests/test_gn_commons.py
- backend/geonature/tests/test_gn_meta.py
- backend/geonature/tests/test_gn_profiles.py
- backend/geonature/tests/test_notifications.py
- backend/geonature/tests/test_permissions.py
- backend/geonature/tests/test_pr_occtax.py
- backend/geonature/tests/test_synthese.py
- backend/geonature/utils/config_schema.py
- contrib/gn_module_occhab/backend/gn_module_occhab/blueprint.py
- contrib/occtax/backend/occtax/models.py
- contrib/occtax/backend/occtax/repositories.py
- data/scripts/import_ginco/import_mtd.py
- pyproject.toml
[Périmètre] lint python 99 vs 100
[Problème]
La doc stipule un line-length de 100, mais la valeur par défaut de black est fixée dans le projet à 99
Doc: https://docs.geonature.fr/development.html#backend
Project configuration `pyproject.toml`: 
```toml
[tool.black]
line-length = 99
```
[Solution]
Forcer le lint à la valeur stipulée dans la doc
Remarque --> si 100 n'est plus une valeur satisfaisante, on peut faire varier la valeur doc et le pyproject conjointement
> fix: update black parameter to meet line-length of 100 chars requirement

- contrib/gn_module_occhab/frontend/app/components/occhab-map-form/occhab-form.component.ts
- contrib/gn_module_occhab/frontend/app/services/form-service.ts
The edition of the `habitats` where broken, when we cancelled the edition, the `habitats` was removed from the list, and if the edition of the `station` was saved the habitats was deleted. Now we save the state of the `habitats` and if we cancel, we reapply it.
> Fix(occhab) fix edit habitats

- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html
Maintenant quand les profiles sont désactiver, on affiche le même titre sans lien.
ref #2820
> fix(obs) adding a non link when no profile

- contrib/occtax/frontend/app/occtax-form/counting/counting.component.html
- contrib/occtax/frontend/app/occtax-form/occurrence/occurrence.component.html
- frontend/src/app/GN2CommonModule/form/data-form.service.ts
- frontend/src/app/GN2CommonModule/form/nomenclature/nomenclature.component.ts
- frontend/src/app/metadataModule/services/actor-form.service.ts
Ajout de la possibilité de personnaliser les nomenclature pour la saisie dans Occtax en fonction du groupe 3 Inpn.
Cette contribution a mené à d'autres contributions au travers des différentes librairies et applications utilisées dans GeoNature, cette PR dépend donc de : 
- https://github.com/PnX-SI/TaxHub/pull/433 : permet d'ajouter un check pour vérifier si la chaîne de caractère fournie est bien un groupe 3 inpn, ce qui dépend également d'une vue matérialisée créée aussi dans cette PR
- https://github.com/PnX-SI/Nomenclature-api-module/pull/53 : permet d'ajouter la colonne à `group3_inpn` à `ref_nomenclatures.cor_taxref_nomenclature` ainsi que les routes API nécessaires pour filtrer les nomenclatures avec le `group3_inpn` et utilise la PR ci-dessus pour vérifier que le groupe3_inpn …
> Feat/Occtax: group3_inpn dans les nomenclatures de saisie

- frontend/src/app/modules/imports/components/import_process/fields-mapping-step/fields-mapping-step.component.html
- frontend/src/app/modules/imports/components/import_process/fields-mapping-step/fields-mapping-step.component.scss
- frontend/src/app/modules/imports/components/import_process/fields-mapping-step/fields-mapping-step.component.ts
[Issue github](https://github.com/orgs/PnX-SI/projects/13/views/15?filterQuery=onglet&pane=issue&itemId=47859830)
[Perimètre] Afficher les entités dans des onglets
Les entités à paramétrer à l'étape 3 (field mapping) de l'import multidestination était affichées les unes à la suite des autres. Le but est de les affichers dans des onglets.
> feat: add tab to handle multiple entities in fields-mapping-step

- backend/geonature/core/imports/tasks.py
- frontend/src/app/modules/imports/components/import_list/import-list.component.html
- frontend/src/app/modules/imports/components/import_list/import-list.component.ts
- frontend/src/app/modules/imports/components/import_process/import-step/import-step.component.ts
- frontend/src/app/modules/imports/imports.module.ts
**Access to import report was broken** from different places: 
1. **From the summary before import**, in step 5 "Import des données", button "Rapport d'import/erreurs/avertissement"    
2. **From the list of imports**, action button "Rapport"
3. **From the notifications ; mail and in-app ;** for an import done
▶️ Path to import report modified with `:destination` parameter added and postponing of right routing from different places.
**Some functionalities for an import from the list of imports were broken**:
1. **Downloading the source file**, click on the filename in the column "Fichier"
2. **Deleting the import**, action button "Supprimer l'import"
▶️ Setting the `destination` parameter for the import data-service in the action functions and thus fixing subsequent calls to API routes …
> fix(import): access to report, download file, delete import

- backend/geonature/tests/imports/conftest.py
When the running unit tests which now includes import, previous tests were failing. This PR fix this issue. 
The double import of fixtures were causing the tests to fails.
> [IMPORT][BACKEND]Fix backend test

- backend/geonature/tests/fixtures.py
- backend/geonature/tests/test_pr_occhab.py
- backend/geonature/tests/utils.py
- contrib/gn_module_occhab/backend/gn_module_occhab/blueprint.py
This PR answers the issue on Occhab when a restricted user tries to modify its own station/habitats.
In addition, this PR change the `create_user()` to enable the creation of test user with detailed scope on one or more actions for a module (or all modules).
Link to the issue : https://github.com/PnX-SI/GeoNature/issues/2909
> Fix Occhab for restricted permissions

- frontend/src/app/modules/imports/components/import_report/import_report.component.html
- frontend/src/app/modules/imports/components/import_report/import_report.component.scss
- frontend/src/app/modules/imports/components/import_report/import_report.component.ts
- frontend/src/app/modules/imports/models/import.model.ts
[Lien Issue](https://github.com/orgs/PnX-SI/projects/13/views/12?pane=issue&itemId=47862422)
A discuter : est ce qu'on affiche le titre du tableau de cette manière : `Entité:....` ou affichage d'une autre manière
Image du rendu coté frontend
> [IMPORT] feat: group field by entity in report

- backend/geonature/core/gn_monitoring/routes.py
- backend/geonature/core/gn_synthese/imports/geo.py
- backend/geonature/core/gn_synthese/utils/blurring.py
Les traitements recommandés dans les deux lignes "todos" ont été appliqués, et les tests sont ok. 
Il me semble que ça suffit à dire que c'est ok.
J'ai rajouté un commit dropable d'ajout de deux todos, en dehors du scope de l'import multi destination, qui me semble du même registre.
> [IMPORT][SYNTHESE] Feat import/use area 4326 instead of sttransform

- backend/geonature/core/gn_synthese/module.py
- backend/geonature/core/imports/models.py
- contrib/gn_module_occhab/backend/gn_module_occhab/module.py
- frontend/src/app/modules/imports/components/import_report/import_report.component.html
Add **destination-specific ; Synthese, OccHab... ; counting statistics in import report**, inside import description panel.
Statistics as for now: 
- Synthese: 
- **Taxa count**
- OccHab: 
- **Stations counts**
- **Habitats count**
Below are screen captures of **imports reports with three representative cases** : 
1. An **import not done** ; more precisely in progress with status 'EN COURS' ; for which statistics are not displayed : 
2. An **import done ; with status 'TERMINE' ; and with destination Synthese**, for which statistics ; count of imported entities and count of imported taxa ; are displayed : 
3. An **import done ; with status 'TERMINE' ; and with destination OccHab**, for which statistics ; count of imported entities, count of imported habitats and count of imported stations …
> [IMPORT] feat(import): add counting statistics in import report

- contrib/gn_module_occhab/backend/gn_module_occhab/migrations/fcf1e091b636_add_constraint_to_th_id_nci_.py
Closes [issue](https://github.com/orgs/PnX-SI/projects/13/views/6?pane=issue&itemId=50172839)
Une révision a été ajoutée au module occhab afin d'ajouter une contrainte manquante `check_t_habitats_id_nomenclature_community_interest` sur le champs `id_nomenclature_community_interest` de la table `pr_occhab.t_habitats`.
Ce dernier doit être de type `HAB_INTERET_COM`.
Cette révision devra surement être squashée avec celle de l'import multi-destination.
> [IMPORT] [OCCHAB]  Add constraint on t_habitats.id_nomenclature_community_interest

- contrib/gn_module_occhab/backend/gn_module_occhab/imports/__init__.py
- contrib/gn_module_occhab/backend/gn_module_occhab/schemas.py
Closes #2921 
Des todos ont été rajoutés sur les portions non couvertes par le test de coverage. 
> `TODO@TestImportsOcchab.test_import_valid_file`
Test réalisé: 
`pytest --cov=./contrib/gn_module_occhab --cov-report xml -k "test_imports_occhab"`
Le compte rendu de ce test de coverage a été filtré pour n'inclure que les éléments liés à l'import.
> [IMPORT][OCCHAB] test: add todos for occhab impor test

- backend/geonature/core/imports/routes/imports.py
- backend/geonature/core/imports/templates/import_template_pdf.html
Les labels des statistics créés dans une property du model `Destination` n'étaient pas utilisés dans le rapport PDF. 
Cette PR permet de s'appuyer cette property `statistics_labels`
> [IMPORT][RAPPORT PDF] Fix/stats labels pdf report

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/GN2CommonModule/GN2Common.module.ts
- frontend/src/app/GN2CommonModule/form/datalist/datalist.component.css
- frontend/src/app/GN2CommonModule/form/datalist/datalist.component.html
Supprime l'utilisation de la librairie "ngx-mat-select-search" qui servait à ajouter un input de recherche sur les composant `mat-select`. Ceci peut être fait sans la librairie
Fix : #2826 et #2827
> remove ngx-mat-select-search - closes #2826 #2827

- frontend/.prettierignore
- frontend/.prettierrc
- frontend/package-lock.json
- frontend/package.json
Closes #2890 
[Périmètre]
Inclure les fichiers html et scss aux vérifications de formattage et formattage.
L'objectif est aussi de trouver un format de sortie à peu près satisfaisant.
- Ajout de règles de lint à la config prettier
- Ajout du repertoire .angular aux contenus ignorés par prettier
- Ajout des fichiers html et scss aux commandes npm de formatages
> [Lint] Extend frontend linting to html and scss files

- .gitmodules
In the .gitmodules file, url given for each submodule can be indicated using relative URL to the parent (here GeoNature git url). It allows to clone both GeoNature and its submodule using the same method (HTTPS or SSH).
> [MAINTENANCE] Change path and remove branch name in `.gitmodules`

- backend/geonature/utils/config_schema.py
resolves #2947 
Source: https://regex101.com/r/iZiUrJ/2
> [BACKEND] Extend authorized PostgreSQL database URI

- frontend/src/app/components/nav-home/nav-home.component.ts
- frontend/src/app/components/sidenav-items/sidenav-service.ts
- frontend/src/app/models/module.model.ts
Lorsque GeoNature est accessible depuis une URL avec un suffixe (demo.geonature.fr/geonature), la redirection du bouton `Accueil` de la page d’accueil ignore ce dernier (demo.geonature.fr/).
Cette PR propose un fix.
Issue à l'origine #2934
> [FIX] Redirection du bouton `Accueil` dans la page d'accueil de GeoNature

- frontend/src/app/GN2CommonModule/map/map.component.ts
> [FRONTEND] Remove multiple loading of tile layers in the map component

- backend/geonature/tests/benchmarks/test_benchmark_ref_geo.py
- frontend/src/app/GN2CommonModule/form/areas/areas.component.ts
- frontend/src/app/GN2CommonModule/form/data-form.service.ts
- frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.html
Add a parameter to remove the geom from the areas query in synthese to gain performances.
By testing with the benchmark tests, the difference was not significative, so i tested with a frontend to see if the serialization of the geoms could take a long time : 
As we can see with a frontend, the serialization takes a lot of time, with those modifications, the process of loading the areas is 3 times faster. The frontend and the backend where both on local, maybe the difference is even bigger on a live instance.
> Feat(areas) add param to remove geom from query

- backend/geonature/app.py
- backend/geonature/core/gn_meta/routes.py
With release 2.14.0 ; and upgrade of Flask from version 2 to 3 ; order of execution for `Flask.before_request` functions calls is no longer well controlled. Besides, setting of the variable `g.current_user` is now made in a `before_request` function. Thus, use of `g.current_user` variable from within another `before_request` function may sometimes not work: this is what prevents the 2 `before-request` functions `set_sentry_context`; in `backend/geonature/app.py`; and `synchronize_mtd`; in `backend/geonature/core/gn_meta/routes.py`; from working properly.
To fix the 2 `before_request` functions, mentioned above, `flask_login.current_user` is used instead of `g.current_user` : 
- Used in `set_sentry_context` to set the user ; ID, username and email ; for Sentry context, if a user is …
> fix(mtd, sentry): get `current_user` from `flask_login` not `g`

- backend/geonature/app.py
Outdated comment `# setting g.current_user on each request` for `load_current_user` before_request function, since `g.current_user` is no longer set by this function.
> chore(create_app.py): remove outdated comment for `load_current_user`

- backend/geonature/core/auth/routes.py
- Add a boolean argument `update_user_organism` to the function `insert_user_and_org` to **possibly prevent update of the id_organism associated to the user** - default to `True`, meaning that the information gets updated by default.
- **Disable update of user organism ; setting the argument to `False` ; when retrieving user and organism information from the webservice 'INPN Authentication' when the user authenticates via CAS INPN**.
> fix(auth, CAS INPN): do not update user organism information from inpn

- frontend/src/app/modules/imports/components/import_process/upload-file-step/upload-file-step.component.ts
Issue: [https://github.com/orgs/PnX-SI/projects/13/views/6?pane=issue&itemId=60872439](https://github.com/orgs/PnX-SI/projects/13/views/6?pane=issue&itemId=60872439)
[Description du problème]
Sur la première page du formulaire d'import, juste après la sélection du module de destination, le champs "jdd" du formulaire est prérempli avec une valeur qui n'existe pas, et crée un état indéterminé. Ce comportement empêche notamment le marquage visuel du champ comme obligatoire (bandeau rouge) ou la sélection automatique du premier jdd s'il éxiste
[Solution]
Je pense qu'il s'ait d'un comportement hérité de la version précédente, qui pré-supposait la définition d'un dataset à l'ouverture de cette page.
J'ai ici simplement supprimé les lignes qui initialise ce champs lors d'une nouvel import. 
Je …
> [IMPORT][FRONTEND] fix: upload-file-step doesn't load a dataset automaticaly

- backend/requirements-dev.txt
- backend/requirements.txt
J'ai fait tourner:
`pip-compile requirements-dev.in`
`pip-compile requirements.in`
Avec pip 24.0 from python 3.9
Pour dev, ce ne sont que des modif attendues. 
Pour l'autre, ça a entrainé l'ajout de pandas --> il était volontairement omis ?
> [IMPORT] fix: regenerate requirements.txt for prod and dev after the addition of bokey

- backend/geonature/core/imports/checks/dataframe/types.py
- backend/geonature/tests/imports/test_dataframe_checks.py
Closes #3003
> Dans le cadre de l'import de données OCCHAB provenant de l'export de ce dernier, le format de date DD/MM/YYYY n'est pas acceptée...
> Pour l'instant le check des dates ne prends pas le format "2015-07-09T10:51:48.805121" en compte, il faudrait faire le point sur les différents format pris en charge et en ajouter le plus possible.
> Peut être en utilisant https://dateparser.readthedocs.io/en/latest/ peut être ajouter des tests pour tester tout les formats de dates.
En fait, le format de date "DD/MM/YYYY" est valide.
Les champs marqués comme date sont vérifiés par **check_dates** (backend/geonature/core/imports/checks/sql/extra.py).
Ce check s'appuit sur la conversion **convert_to_datetime** (backend/geonature/core/imports/checks/dataframe/types.py).
Cette conversion prends …
> [IMPORT][BACKEND] improve date format available

- frontend/src/app/modules/imports/components/import_report/import_report.component.html
- frontend/src/app/modules/imports/components/import_report/import_report.component.scss
- frontend/src/app/modules/imports/components/import_report/import_report.component.ts
Cette PR porte sur l'issue #3039 
Elle traite la partie 
> Il est nécessaire d'ajouter dans le tableau la correspondance avec le nom standard SINP pour s'assurer que le mapping est correcte car les champs en base ne sont pas toujours clairs -=(count_min, count_max).
Afin de remplir ce besoin fonctionnel, cette PR propose de rajouter une colonne qui affiche le contenu du champs commentaire dans Import > Report > Correspondances > Champs
Cette solution a été discutée ici
https://matrix.to/#/!EqtcZxjaNkyMQFGHgg:matrix.org/$GmoLRnJKmRytsaUPCnaQvxLt_Qky1d3kFxI2ViPoWQE?via=matrix.org&via=sdfa3.org
La seule subtilité porte sur la structure de donnée affichée, qui a été transformée d'un dictionnaire: source -> destination en un tableau d'un objet comprenant source, destination et commentaire
> [IMPORT][FRONTEND] feat: add "description" column in Correspondances > Champs array

- backend/geonature/core/auth/routes.py
- frontend/src/app/app.module.ts
- frontend/src/app/components/auth/auth.service.ts
- frontend/src/app/modules/login/login/login.component.ts
- frontend/src/app/modules/login/routes-guard.service.ts
- frontend/src/app/routing/app-routing.module.ts
Fix authentication via CAS INPN.
> [AUTH CAS INPN] fix(auth): fix authentication via CAS INPN

- backend/geonature/core/gn_meta/mtd/__init__.py
Two lines were was referred `requests.HttpError` instead of `requests.HTTPError`.
> fix(mtd): fix typo error for catch of `requests.HTTPError`

- frontend/.nvmrc
Angular supports node in its latest LTS version (20) : https://github.com/angular/angular-cli/pull/26173
> [MAINTENANCE] Update NodeJS to version 20

- backend/geonature/core/gn_meta/mtd/mtd_utils.py
Modify the function `sync_af` so that it returns the actual acquisition framework ; an instance of the model `TAcquisitionFramework` ; rather than an integer.
This, in turn, fixes the function `process_af_and_ds` and fixes MTD synchronization.
> fix(mtd): make `sync_af` return actual af model and not int

- contrib/gn_module_occhab/backend/gn_module_occhab/imports/plot.py
Problem: 
The plot method was still generating a figure even if no valid data were found.
A short test on the content of the figures array has been added, and the method return None if the array is empty. 
It leads to the disparition of the plot on the frontend, wich is the expected behavior.
> [IMPORT][OCCHAB] Fix: add "no figure" handling in occhab plot

- backend/geonature/core/gn_synthese/imports/synthese_import_mixin.py
Cette PR dépend de la PR #3007 qui fait apparaître le mixin de l'import.
Cette toute mini PR corrige le problème suivant en ajoutant un check sur les données.
> [IMPORT][BACKEND][SYNTHESE] Fix import: add "no data" handling in synthese plot

- backend/geonature/core/imports/checks/sql/extra.py
Le problème qui a été remonté (https://github.com/PnX-SI/gn_module_import/issues/504), est que il est possible pour GeoNature de générer une altitude négative, ce qui cause une erreur.
Dans cette PR j'ai retiré le check pour voir si l'altitude est négative, est-ce la meilleure solution à retenir ou faudrait-il mieux empêcher la génération d'altitude négative ?
> [IMPORT] Allow negative altitude

- backend/geonature/core/gn_synthese/imports/synthese_import_mixin.py
- backend/geonature/core/imports/config_schema.py
- backend/geonature/core/imports/models.py
- frontend/src/app/modules/imports/components/import_list/import-list.component.html
- frontend/src/app/modules/imports/components/import_list/import-list.component.ts
- frontend/src/app/modules/imports/components/import_report/import_report.component.html
- frontend/src/app/modules/imports/components/import_report/import_report.component.ts
- frontend/src/app/modules/imports/utils/format-row-count.ts
- frontend/src/styles.scss
Closes #3070
Cette PR concerne l'affichage du résumé des données importées dans la page liste import. 
La statistique commune "nombre d'entité importée" a été remplacé par une portant sur le nombre de ligne importées. 
Une statistique portant sur le nombre d'observations importées a été rajoutée.
A l'affichage, on souhaite la combinaison de plusieurs données. 
La donnée affichée n'est donc plus une propriété directement, mais un formatage propre à cette section du frontend. 
Divers labels ont été mis à jour sur la liste d'import ou le rapport d'import. 
- Liste des imports: Nb de données --> Lignes importées
- Rapport d'import: Nombre de lignes importées
- Statistiques de la synthèse: ajout des observations, et reformulation "Nombre de taxon"
Une mise à jour du layout de la popup de …
> [IMPORT][LISTE] fix informations displayed on liste import

- backend/geonature/core/gn_commons/models/abstract_mixin.py
- backend/geonature/core/gn_synthese/module.py
- backend/geonature/core/imports/import_mixin.py
- contrib/gn_module_occhab/backend/gn_module_occhab/module.py
C'est une PR proposition: vous pouvez la supprimer, je ne me vexe pas :)
On observe des warnings liés au polymorphisme, et à l'abstraction sur les modules. 
Le fait de basculer de l'approche _du module_ `ABC` à l'approche _artisanale_ `raise NotImplementedError` supprime ces warnings. 
Je fais confiance aux tests pour voir si ça fonctionne correctement :)
```bash
/home/etienne/Documents/devel/geonature/ns-github/geonature_import/geonature/backend/venv/lib/python3.10/site-packages/flask_sqlalchemy/model.py:120: SAWarning: 
Mapper mapped class TModules_SyntheseImportMixin->t_modules does not indicate a polymorphic_identity, yet is part of an inheritance hierarchy that has a polymorphic_on column of 't_modules.type'.  
Objects of this type cannot be loaded polymorphically which can lead to …
```
> [IMPORT] [BACKEND] [CHORE] chore: replace abc abstract by raise NotImplementedError in ImportMixin

- backend/geonature/tests/test_validation.py
To avoid errors when running tests without validation module installed.
> fix(tests): move import after importorskip

- backend/geonature/core/imports/routes/imports.py
modues were missing from joined informations
> fix "1+n" issue in import list

- .github/workflows/pytest.yml
- docs/tests_backend.rst
- pyproject.toml
This PR propose to disable benchmark automatic launch when running pytest.
To run the benchmarks, you have to run the following command:
```shell
pytest --benchmark-only
```
> feat(pytest) : Disable defaut launch of benchmark

- .gitignore
> fix: add gitignore to custom folder instead of gitkeep

- contrib/gn_module_occhab/backend/gn_module_occhab/migrations/aed662bbd88a_add_default_mapping.py
This PR propose to include new mapping dedicated to the OccHab destination.
> [IMPORT][OCCHAB] add default mapping

- backend/geonature/core/gn_synthese/synthese_config.py
- frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.html
- frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.scss
Closes #2718 
Voir l'issue pour plus de détail sur le sujet développement réalisé.
Il me semble que la réflexion amenait à peu près à ce mini-dev, pour se rendre compte de ce à quoi ça ressemblerait. 
Le développement en lui-même est assez sobre, et peut se passer de commentaire.
> feat: add link to taxon sheet in synthese list

- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs-container.component.ts
- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html
- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts
- frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.html
- frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.ts
- frontend/src/app/syntheseModule/synthese.component.html
- frontend/src/app/syntheseModule/synthese.component.ts
- frontend/src/app/syntheseModule/synthese.module.ts
- Manage dynamic tabs displayed (using tabs object with path and label)
- Add route 'occurrence/:id_synthese/:tab'
- Add manage event when modal is closed (go back to module 'synthese')
- Apply lint frontend
- Add "TODO" --> delete openInfoModal in syntheseListComponent because using routerLink to openModal
Concernant le TODO, pour moi on peut tout simplement supprimer la method "openInfoModal" vu qu'on utilise dans les devs proposés une manière plus classique à savoir l'utilisation du routerLink.
[Refs_Issue] : #3155 
> feat: add route to tabs synthese info

- frontend/src/app/GN2CommonModule/map/leaflet-draw/leaflet-draw.component.ts
- Refact and manage use case where the user wants to create new geometrie  --> saved --> and wants to edit the geom created
[Refs_tickets] : #3195 
Closes #3195
> fix: duplicated geom "not saved" on edition

- frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.html
- frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.scss
Cette PR propose de résoudre le problème d'UX concernant le composant radio bouton .
Voici les images présentant la solution mise en place (le premier radio bouton est non obligatoire et le deuxième radio bouton Scope est obligatoire):
----------------------------------------
[Refs_issue] : closes #3210 
> fix: radio button invalid form

- backend/geonature/core/imports/routes/imports.py
- backend/geonature/core/imports/templates/import_template_pdf.html
- backend/geonature/core/imports/utils.py
- frontend/src/app/modules/imports/components/import_report/import_report.component.html
- frontend/src/app/modules/imports/components/import_report/import_report.component.ts
This PR proposes to update the design and information displayed in the report for an import.
Exemple nouvel export PDF : [import_347_2024-10-09 16_06_11.310403_report-8.pdf](https://github.com/user-attachments/files/17339848/import_347_2024-10-09.16_06_11.310403_report-8.pdf)
> [IMPORT] update import report  

- backend/geonature/core/gn_meta/models/aframework.py
- backend/geonature/core/gn_meta/routes.py
- backend/geonature/tests/fixtures.py
- backend/geonature/tests/test_gn_meta.py
- frontend/src/app/metadataModule/af/af-card.component.html
- frontend/src/app/metadataModule/af/af-card.component.scss
- frontend/src/app/metadataModule/af/button-delete-af.component.html
- frontend/src/app/metadataModule/af/button-delete-af.component.ts
- frontend/src/app/metadataModule/metadata.component.html
- frontend/src/app/metadataModule/metadata.module.ts
Closes #1673 
On souhaite ici permettre la suppression d'un Cadre d'Acquisition (CA).
Un CA peut être supprimé si et seulement si: 
- il ne contient pas de dataset
- il n'est pas le parent d'un autre CA
Le modèle a été modifié pour transformer "is_deletable" en deux fonctions, qui explicitent le critère.
- has_datasets
- has_child_acquisition_framework
La route existante, mais non utilisée, a été conservé. Le critère de possibilité de suppression a été ajusté à la suppresion du modèle
Le composant `button-delete-af` a été ajouté. 
Il permet, à partir d'un cadre d'acquisition donné, de réaliser la suppression avec dialog de confirmation. 
Ce bouton a été intégré au composant metadata (metadata.component) et à la page de description d'un cadre d'acquisition (af-card.component).
Le layout du …
> [GN_META] Allow for acquisition framework deletion

- backend/geonature/tests/imports/files/occhab/valid_file.csv
- backend/geonature/tests/imports/test_imports_occhab.py
- backend/geonature/tests/test_pr_occhab.py
- contrib/gn_module_occhab/backend/gn_module_occhab/blueprint.py
- contrib/gn_module_occhab/backend/gn_module_occhab/imports/actions.py
- contrib/gn_module_occhab/backend/gn_module_occhab/imports/checks.py
- contrib/gn_module_occhab/backend/gn_module_occhab/models.py
This PR propose a new check to verify if a user got required permissions to import a new habitat in an existing station.
> [IMPORT] check permission when habitat is imported on existing station

- frontend/src/app/modules/imports/components/import_list/import-list.component.html
- frontend/src/app/modules/imports/components/import_list/import-list.component.scss
- frontend/src/app/modules/imports/components/import_process/import-step/import-step.component.html
- frontend/src/app/modules/imports/components/import_report/import_report.component.html
- frontend/src/app/modules/imports/components/import_report/import_report.component.scss
Cette PR porte sur le layout 
Ceci est une proposition.
J'ai fait un essai de refacto de la page importe report, pour qu'elle soit plus cohérente avec la liste des imports.
Modifications: 
- marge et padding un peu partout
- containers de section de material à boostrap
- le header (précédent, titre, status) sur une seule ligne
- taille des polices, des icones, des titres ajustées.
- équilibre horizontal contenu / bouton en faveur du contenu
Rapport d'import
Liste des imports
> [IMPORT] [FRONTEND] [PROPOSITION] Modification du layout du rapport d'import

- docs/FAQ.rst
- docs/admin-manual.rst
- docs/development.rst
- docs/https.rst
- docs/installation-all.rst
- docs/installation-docker.rst
- docs/installation-standalone.rst
- docs/installation.rst
As TaxHub has been integrated in GeoNature in its 2.15 version
> Documentation - Remove external TaxHub references

- .github/workflows/gn-module-pytest.yml
Action réutilisable par les modules GeoNature pour lancer les tests pytest.
Usage:
```
name: pytest
on:
push:
branches:
- main
- develop
pull_request:
jobs:
build:
uses: pnx-si/geonature/.github/workflows/gn-module-pytest.yml@master
with:
geonature_ref: "develop"
```
Exemple: https://github.com/PnX-SI/gn_module_permrequests/blob/main/.github/workflows/pytest.yml
Perspectives :
- configurer la commande d’installation
- configurer la commande de test
- activer l’envoi du code coverage → fait, à tester
- si la ref geonature n’est pas fournit, utiliser la ref de l’action plutôt que master (ce qui revient au même si on utilise la version master de l’action) (pas si simple, voir cf https://github.com/dariocurr/checkout-called)
> feat(workflows): add reusable pytest actions

- backend/geonature/core/gn_monitoring/models.py
- backend/geonature/core/gn_monitoring/routes.py
- backend/geonature/migrations/versions/6734d8f7eb2a_monitoring_add_id_digitizer_to_t_observations.py
- backend/geonature/migrations/versions/8309591841f3_monitoring_add_observers_txt_column_t_base_visit.py
- backend/geonature/migrations/versions/9b88459c1298_monitoring_create_t_observations.py
- backend/geonature/migrations/versions/a54bafb13ce8_monitoring_create_cor_module_type.py
- backend/geonature/migrations/versions/b53bafb13ce8_monitoring_create_bib_type_site.py
- backend/geonature/migrations/versions/ce54ba49ce5c_monitoring_create_cor_site_type.py
- frontend/src/app/GN2CommonModule/form/datalist/datalist.component.ts
- frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.html
- frontend/src/app/GN2CommonModule/form/observers/observers.component.ts
https://github.com/PnX-SI/gn_module_monitoring/issues/271
En lien avec : https://github.com/PnX-SI/gn_module_monitoring/pull/285
> Manage models in geonature not gn_module_monitoring

- backend/geonature/core/gn_synthese/routes.py
- frontend/src/app/components/home-content/home-discussions/home-discussions-table/home-discussions-table.component.ts
Ajout d'un petit fix pour régler le problème de la pagination quand on utilise le switch de mes discussions. 
La pagination est maintenant réinitialisée lors de la mise à jour de la valeur de "Mes discussions".
Au passage, deux trois petits refacto de simplification des paramètres de pagination sur la route appelée
> fix: tiny fix on home discussions table

- backend/geonature/core/gn_monitoring/models.py
- backend/geonature/migrations/versions/df277299fdda_add_id_import_column_for_each_entity.py
https://github.com/orgs/PnX-SI/projects/13/views/6?pane=issue&itemId=83657166
> add id_import in monitoring model

- docs/CHANGELOG.md
A long due change ! This PR propose to parse the changelog.md... to an actual markdown formated file :D
> feat(changelog): parse to markdown

- .gitignore
- Makefile
This PR propose developer oriented shortcuts using a MakeFile.
This allows : 
- run install backend
- run install frontend
- run creation of the stock database of GeoNature
- run the celery worker
- run the backend
- run the frontend
- show database status
TODO 
Discussed in #3300
> feat(dev): add Makefile to include dev (only?) shortcuts

- backend/geonature/core/gn_synthese/routes.py
This PR fix a performance issue caused by the new route `list_all_reports`
> fix(reports): refact `list_all_reports` route to not load all synthese ids

- backend/geonature/core/gn_synthese/routes.py
- backend/geonature/migrations/versions/5cf0ce9e669c_create_index_on_synthese_observers.py
- backend/geonature/tests/benchmarks/test_benchmark_home.py
closes #3309 
Based on propositions made by @dba-sig-sfepm
Includes :
- update of the `general_stats` route
- new benchmark test
- new index on the `observers` column of the `gn_synthese.synthese` column
> feat(home): optimize `general_stats` route

- backend/geonature/core/command/main.py
This PR propose to change `geonature dev_back` commands so it restart the flask service when the `geonature_config.toml` is edited
> feat(commands): watch for geonature_config.toml changes when dev_back running

- backend/geonature/core/gn_synthese/routes.py
- backend/geonature/tests/test_utils.py
- backend/geonature/utils/config.py
- backend/geonature/utils/config_schema.py
- config/default_config.toml.example
- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html
- frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.html
- frontend/src/app/syntheseModule/synthese.module.ts
- frontend/src/app/syntheseModule/taxon-sheet/taxon-sheet.route.service.ts
Closes #3311 
- Ajout de l'option ENABLE_TAXON_SHEETS
- Modification des options SYNTHESE.TAXON_SHEET.ENABLE_XXX en SYNTHESE.TAXON_SHEET.ENABLE_TAB_XXX
> [CONFIG] Taxon sheet and config

- backend/requirements-dependencies.in
- backend/requirements-dev.txt
- backend/requirements.txt
The downgrade of cryptography from 44.0 to 43.x is due to an incompatibility of the latest version with python 3.9 and python 3.9.1 . Check https://pypi.org/project/cryptography/
> bump taxhub to 2.1.1

- backend/geonature/core/gn_synthese/routes.py
- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
- backend/geonature/tests/benchmarks/test_benchmark_home.py
> fix(general_stats): re-enable cruved on the stats computed

- backend/geonature/utils/config_schema.py
- docs/CHANGELOG.md
Since GeoNature 2.15, connect to other identity providers was made possible. However, sensible configuration variable were made accessible in the frontend config returned in the public route `gn_commons/config`.
**A notice must be made in GeoNature 2.15.0 and 2.15.1 to warn users to update the 2.15.2 version if they wish to use such functionnality !**
> fix(login): hide external connection portal configuration to frontend configuration

- .github/workflows/sphinx.yml
- docs/admin-manual.rst
This PR proposes to change the publication process of the documentation. To allow hot-fix on the doc without releasing a new version of GeoNature. An example is given by a wrong path leading to a .rst file.
> feat(doc): publish documentation on push action on master branch

- backend/geonature/core/gn_synthese/utils/blurring.py
Set final order_by on id_synthese from ascending to descending - so as to retrieve up-to-50000 more recent rather than least up-to-50000 recent observations from the up-to-100000 observations of 2 unioned subqueries - for Synthese queries involving blurring.
> fix(synthese): set order_by descending id_synthese to prior last

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/app.module.ts
- frontend/src/app/components/auth/auth.service.ts
- frontend/src/app/modules/login/login/login.component.ts
- frontend/src/app/modules/login/routes-guard.service.ts
- frontend/src/app/routing/app-routing.module.ts
- frontend/src/app/routing/auth-guard.service.ts
- frontend/src/app/services/module.service.ts
Several fixes:
- Fix direct public access with query param when INPN CAS authentication is configured
- Fix flaky login and logout - ref https://github.com/PnX-SI/GeoNature/issues/3353
- Use AuthGuard rather than UserCasGuard on NavHomeComponent, and remove UserCasGuard definition
- Handle the case where a user is no more authenticated server-side but still authenticated client-side, by calling frontend logout()
- Fix login and logout for Firefox clients :
- Replace legacy library Moment.js with library Luxon
- Fix frontend logout() by waiting for backend logout return before redirection to login page
Chore:
- Remove unused Router and AuthService from ModuleService constructor
> [FIX][AUTH] Fix Public Access with CAS INPN and other bugs

- backend/geonature/tests/benchmarks/test_benchmark_synthese.py
- backend/geonature/tests/benchmarks/utils.py
> fix(test): revert to dedicated user in blurring performance evaluation

- backend/geonature/core/imports/config_schema.py
- config/default_config.toml.example
Ce paramètre activé par défaut est discutable, et surtout posait pas mal de soucis aux utilisateurs depuis GeoNature 2.15 : https://github.com/PnX-SI/gn_module_import/issues/515
Déjà mentionné en 2021 : https://github.com/PnX-SI/gn_module_import/issues/216
Donc on le passe à False par défaut.
> config(import) Set CHECK_PRIVATE_JDD_BLURING default to False

- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/taxonomy/taxonomy.component.html
- frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/taxonomy/taxonomy.component.ts
- frontend/src/app/syntheseModule/taxon-sheet/taxon-sheet.service.ts
Un fix a été fait dans la PR: #3384 (https://github.com/PnX-SI/GeoNature/pull/3384)
Sur demande de Camille, j'ai fait un ptit passage sur le fix réalisé. 
J'ai changé l'approche ngChange + ngInit par un accesseur en ecriture sur le taxon.
Comme on a deja l'input comme évènement déclencheur, il suffit de rajouter un traitement à cet endroit la. Pas besoin de la lourdeur d'un watcher supplémentaire. 
Au passage, j'ai corrigé l'affichage des attributs, qui n'était pas bon. 
- champs affiché dans le html (synthese + fiche espèce)
- ajout du label dans la requête (fiche espèce)
> Refacto: fix on taxonomy status

- .github/workflows/cypress.yml
- .github/workflows/pytest.yml
- frontend/cypress/e2e/occhab-spec.js
Using populated database image is up and working !
| GHActions         | Before - Execution time (minutes) | Nouveau temps (minutes) |
|-------------------|------------------------|-------------------------|
| Pytest(Debian 11) | ~12                     | ~8                       |
| Pytest(Debian 12) | ~11                     | ~6                       |
| Cypress           | ~26                    | ~16          |
> feat(test): Use populated db image

- .pre-commit-config.yaml
Modifie le pré-commit pour qu'on ne soit plus obligé d'utiliser python3.9. 
closes #3356
> feat(pre-commit): change default python for pre-commit.

- backend/geonature/app.py
- backend/geonature/core/command/create_gn_module.py
- backend/geonature/tests/test_commands.py
- backend/geonature/utils/module.py
- Possibilité d’installer un module sans frontend
- Possibilité d’installer un module sans config
- Possibilité de personnaliser le label du module
- Possibilité de personnaliser le chemin de l’API du module
> Améliorations de la commande d’installation des modules

- contrib/gn_module_occhab/backend/gn_module_occhab/migrations/5fe452b34a79_make_nom_cite_mandatory_in_import.py
Dans l'import, le champs "nom_cite" n'est pas marqué comme obligatoire. Pourtant il l'est :)
> Fix: occhab import nom cite

- backend/geonature/app.py
- backend/geonature/core/health/routes.py
- backend/geonature/tests/test_health.py
https://github.com/PnX-SI/GeoNature/issues/3417
- Add `/healthz` that indicates if redis, celery worker and the database connection are good
- add `/services_status` that give detailed informations on which related services works or not
Example : 
```JSON
{
"services": [
{
"message": "The database is available",
"name": "database_connection",
"status": "ONLINE"
},
{
"message": "The redis server is available",
"name": "redis_connection",
"status": "ONLINE"
},
{
"message": "The celery worker is available",
"name": "celery_worker",
"status": "ONLINE"
}
]
}
``` 
TODO
> add route to check API health #3417

- backend/geonature/migrations/data/core/synthese.sql
Without the public key I meet errors using fdw (foreign data wrapper) when I want to insert data in gn_synthese.synthese table
> Update synthese.sql adding "public" schema reference

- .github/workflows/cypress.yml
- backend/geonature/core/notifications/models.py
- backend/geonature/core/notifications/routes.py
- backend/geonature/migrations/versions/0bea266db3ec_hide_unauthorized_notifications.py
- backend/geonature/migrations/versions/95acee9f0452_add_comment_notification.py
Fixes #3262
- Pour import, il faut une permission sur le module import objet import, n’importe quelle action.
- La prochaine version du module d’export pourra rajouter une contraintes identiques.
- Pour la modification du statut de validation ou le commentaire sur une observation, les notifications sont envoyées aux observateurs et au digitaliser. En conséquence, pas de contrainte.
- Pour les demandes de permissions, il y aura une contraintes action C pour les notifs au demandeur, et une contrainte action V pour les notifs aux admins.
> feat(notifications): hide unallowed categories

- backend/geonature/tests/conftest.py
- backend/geonature/tests/fixtures.py
- backend/geonature/tests/test_gn_meta.py
- backend/geonature/tests/test_synthese.py
Cette PR intègre à GeoNature ce qui a été fait dans https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/pull/36
Une limitation de longue date à la fixture `temporary_transaction` est qu’elle ne s’applique qu’au niveau du scope `function`. Cela veut dire que toutes les modifications de la base effectuées dans des fixtures ayant toute autre scope que `fixture` sont conservées entre les tests. Elles sont seulement supprimées à la fin de l’ensemble des tests grâce à ce « hack » dans la fixture `app` : https://github.com/PnX-SI/GeoNature/blob/f23db179c81f76128be4ba7fa112934eda0c1876/backend/geonature/tests/fixtures.py#L119-L121
Or souvent il est utile de réutiliser des fixtures pour l’ensemble d’une classe ou d’un module de tests. Par exemple les utilisateurs, modules, objets, JDD et CA dans les …
> use all-scope temporary transactions

- backend/geonature/app.py
- backend/geonature/tests/test_utils.py
- backend/geonature/utils/json.py
- docs/development.rst
Pagination : Flask-SQLAlchemy fournit l’utilitaire [`db.paginate`](https://flask-sqlalchemy.readthedocs.io/en/stable/api/#flask_sqlalchemy.SQLAlchemy.paginate). Notons qu’il n’est pas nécessaire de récupérer les paramètres ``page`` et ``per_page`` de la requête puisque cela est fait automatiquement par ``db.paginate``. Par ailleurs, l’objet [Pagination](https://flask-sqlalchemy.readthedocs.io/en/stable/api/#flask_sqlalchemy.pagination.Pagination) créé par ``db.paginate`` peut directement être renvoyé passé à ``jsonify`` par votre route ; il sera sérialisé dans [une structure commune à l’ensemble de l’application](https://github.com/PnX-SI/GeoNature/blob/feat/json-pagination/backend/geonature/utils/json.py). Ce mécanisme nécessite que le schéma Marshmallow nécessaire à la sérialisation des …
> Sérialisation des objets Pagination pour un usage simple et homogène de db.paginate

- config/default_config.toml.example
- docs/admin-manual.rst
Quelques ajustements de la doc sur la custo des traductions.
Je pense qu'il faudrait préciser aussi comment ajouter une nouvelle langue. 
Et à quoi servent les paramètres actuels `MULTILINGUAL` et `DEFAULT_LANGUAGE`.
Plus largement, il manque aussi certainement un paramètre `AVAILABLE_LANGUAGE` pour pouvoir définir les langues proposés aux utilisateurs.
> Review admin-manual (custom translations)

- backend/geonature/core/gn_permissions/models.py
- contrib/gn_module_validation/backend/gn_module_validation/blueprint.py
- contrib/gn_module_validation/backend/gn_module_validation/migrations/beee577de116_extended_permissions.py
Pas de filtre de type sensibilité, car ça semble peu commun de refuser à un validateur l’accès aux données floutées, et comme ça pas besoin de gérer le floutage des données sensibles dans le module validation.
On pourra le rajouter dans le futur si besoin, mais dans ce cas il faudra plutôt exclure les données sensibles que les flouter, car vraiment aucun sens de faire de la validation sur des données floutées.
> validation: support taxons & areas perm filters

- backend/geonature/core/gn_synthese/utils/blurring.py
- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
See #3566 and #3571.This fix improves the speed of Synthese query when a geographic area filter has been used.
> Fix: remove blurred observations outside filtered municipality

- backend/geonature/core/gn_permissions/models.py
- backend/geonature/core/gn_synthese/blueprints/synthese.py
- backend/geonature/core/gn_synthese/blueprints/taxon_info.py
- backend/geonature/core/gn_synthese/utils/blurring.py
- backend/geonature/core/gn_synthese/utils/query_select_sqla.py
- backend/geonature/core/gn_synthese/utils/taxon_sheet.py
- backend/geonature/tests/test_synthese.py
- docs/sensitivity.rst
- frontend/src/app/GN2CommonModule/form/synthese-form/synthese-data.service.ts
- frontend/src/app/syntheseModule/taxon-sheet/taxon-sheet.route.service.ts
This PR resolves issues raised during the pre-release test of GeoNature 2.16.0
This PR add the following:
- apply new filters on the taxon sheet
- change taxon sheet route naming
- add warning entry in the documentation regarding blurring with id_nomenclature_sensitivity empty  
- Add new test to verify if the taxonsheets routes raise Forbidden when a user try to fetch info on a taxon which is not authorized for him
- Complete test of Geo/Taxo filters when recovering observations in the Synthese with and without a sensitivity filter
- change the `__repr__` method of `Permission` to ease the debug related to permissions
> [2.16-dev] Fix application of new taxonomic/geographic filters on TaxonSheet and Synthese

- backend/geonature/core/gn_meta/routes.py
- frontend/src/app/metadataModule/metadata.component.html
At the moment the only permission needed for publishing an AF is export. However, publishing an AF close it, so it effectively update it.
> fix: Put Update permission on publishing AF instead of export

- config/default_config.toml.example
Ajout de l'entrée manquante dans la config PERMISSIONS > GEOGRAPHIC_FILTER_AREA_TYPES
(https://matrix.to/#/!gJfHSUgjLUSdSyZfkn:matrix.org/$dokVOh0FSSVYIeUQSzI9t1qZ7f7eXn4tH2b0UJwf5ww?via=matrix.org&via=matrix.makina-corpus.net&via=moon.org.nz)
> Fix: Add missing permissions areatype entry in documentation
