data/2154/contactflore.sql
Modifs de la fonction contactflore.insert_releve_cflore (erreurs sur nom de table)
Ajout de la fonction synthese.calcul_cor_unite_taxon_cflore manquante 
Modifs du trigger synthese.maj_cor_unite_taxon pour prendre en charge la flore
=> Modification du contact flore pour les couleurs

lib/model/doctrine/BibTaxonsTable.class.php
Remarquée à travers une erreur récurrente dans mes logs de postgresql
Pas sûre des implications applicatives...
=> Petite erreur de frappe sur le nom du schéma

data/update_1.7to1.8.sql
Ajout insert_releve_cflore et update_releve_cflore
=> Manque 2 MAJ de fonctions pour le contactflore

data/2154/contactflore.sql
renvoyait une erreur lors d'un update de contact flore
=> coquille dans le trigger synthese_update_fiche_cflore

web/js/synthese/application.synthese.search.js
Mise au format YYYY-MM-DD plutôt que DD-MM-YYYY.
=> Changement du nom des fichiers exportés

config/settings.ini.sample, install_app.sh, install_db.sh
Allow DB hostname configuration from global settings and remove hardcoded 'geonatdbhost'
=> db host configuration

backend/geonature/core/gn_commons/models.py
Correction du modèle TModules où  module_target est déclaré 2 fois.
=> field module_target declared twice in TModules

backend/geonature/utils/utilssqlalchemy.py
=> fix GenericQuery.build_query_filter() param_name substitutions.

docs/admin-manual.rst
droit taxonomique non fonctionnels pour l’instant
#563
=> update doc (admin manual, permissions)

frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.html
Correctif pour l'ouverture de la fenêtre des filtres avancés de la taxo.
=> [Synthèse] Correctif dynamic form

docs/admin-manual.rst
Update admin docs :
* backup and restore part
* occtax part (generate full taxon lists)
=> Few docs updates 

contrib/gn_module_validation/frontend/app/components/validation-definitions/validation-definitions.component.ts, contrib/gn_module_validation/frontend/app/components/validation-modal-info-obs/validation-modal-info-obs.component.ts, contrib/gn_module_validation/frontend/app/components/validation-popup/validation-popup.component.ts
Oups, mauvaise base associée à la première PR je recommence... Prend les remarques de #709
=> Quelques corrections sur le module validation

backend/geonature/core/gn_synthese/routes.py, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-data.service.ts
=> Requete d'interogation de la synthese en POST plutôt que GET

backend/geonature/core/command/create_gn_module.py, backend/geonature/utils/env.py
issue #764 : installation des requirements à l'installation d'un module
=> module requirements

backend/geonature/core/gn_commons/routes.py
Dans la route pour insérer ou modifier un média
Modification pour prendre en compte les paramètres de route form de type boolean
=> Route media

data/core/commons.sql, data/migrations/2.2.1to2.3.0.sql, docs/CHANGELOG.rst
Ajout de contrainte UNIQUE pour les champs module_code et module_path de gn_commons.t_modules
=> module code path unique

contrib/occtax/frontend/app/occtax-map-form/form/occtax-form.component.ts
Il y a peut être mieu à faire mais bon
=> Fichier GPX est concervé lors de l'enchainement des relevés - cf #813

docs/admin-manual.rst
Corrections de quelques typos mineures en cours de lecture de la documentation administrateur.
=> correction de quelques typos dans la doc administrateur

config/default_config.toml.example
Add more comments (for all properties).
Translate all comments in french.
Fix some properties values.
=> Doc default_config.toml.example: add comments

frontend/src/app/GN2CommonModule/map/geojson/geojson.component.ts
The layer Layer not have getBounds() method.
=> Fix CommonMod/GeoJson: use GeoJSON Leaflet layer

frontend/src/app/maintenance/LogoGeonature.jpg, frontend/src/app/maintenance/index.html
Add logo image file in current maintenance directory.
Try to use symbolic link.
=> Fix maintenance: update logo image path

backend/geonature/core/gn_synthese/routes.py, frontend/src/app/GN2CommonModule/form/data-form.service.ts, frontend/src/app/metadataModule/datasets/dataset-card.component.ts
étant donné qu'il y a beaucoup plus de catégories à afficher j'ai fait un code pour générer un nombre arbitraire de couleurs. Puis je me suis dit que les couleurs par défaut étaient beaucoup plus faciles à lire, mais j'ai gardé mon code en commentaire au cas où Judith préférerait un dégradé de bleu comme dans son modèle.
=> Feature/ginco2-45 : Répartition des espèces

frontend/src/app/GN2CommonModule/form/multiselect/multiselect.component.ts
Fix #885, test if we have values before try to deduplicates them.
=> Fix multiselect: try deduplicate only if values exist

contrib/gn_module_validation/frontend/app/components/validation-modal-info-obs/validation-modal-info-obs.component.html
=> Revert "correction coquille : existance --> existence"

data/core/commons.sql, data/migrations/2.4.3to2.4.4.sql, data/migrations/v2.4.1to2.4.2.sql
=> Ajout d'une contrainte d'unicité sur la table gn_commons.t_parameters sur le duo de champs id_organism, parameter_name

frontend/src/app/GN2CommonModule/GN2Common.module.ts, frontend/src/app/GN2CommonModule/form/data-form.service.ts, frontend/src/app/GN2CommonModule/form/date/date.component.html, frontend/src/app/GN2CommonModule/form/date/date.component.ts, frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.html, frontend/src/app/GN2CommonModule/form/multiselect/multiselect.component.html, frontend/src/app/GN2CommonModule/form/multiselect/multiselect.component.scss, frontend/src/app/GN2CommonModule/form/multiselect/multiselect.component.ts, frontend/src/app/GN2CommonModule/form/taxa/taxa.component.html, frontend/src/app/GN2CommonModule/form/taxa/taxa.component.ts
See description in commits detail.
Close #1069, #1068, #1067 and #1065.
=> Feat frontend/common: improve dynamic-form, pnx-date

docs/development.rst
Global RST review, thanks to http://rst.ninjs.org/
The page preview was broken.
Titles, lists blank lines, no line breaks in lists...
Still a few parts to fix.
=> DOC DEV - Global layout review

contrib/occtax/frontend/app/occtax-form/occurrence/occurrence.service.ts
=> Occtax - preuve existence

frontend/src/app/GN2CommonModule/form/areas/areas.component.html, frontend/src/app/GN2CommonModule/form/areas/areas.component.ts, frontend/src/app/GN2CommonModule/form/taxa/taxa.component.html, frontend/src/app/GN2CommonModule/form/taxa/taxa.component.ts
=> Fix frontend/gn2common: add 'disabled' input to pnx-taxa & area

frontend/src/app/GN2CommonModule/GN2Common.module.ts, frontend/src/app/GN2CommonModule/others/breadcrumbs/breadcrumb.interface.ts, frontend/src/app/GN2CommonModule/others/breadcrumbs/breadcrumbs.component.html, frontend/src/app/GN2CommonModule/others/breadcrumbs/breadcrumbs.component.ts
=> Feat frontend/gn2common: add breadcrumb component

backend/geonature/core/gn_meta/routes.py, frontend/src/app/metadataModule/metadata.component.html
Merge the feat branch with develop to get the recent updates, add a constraint to deactivate the deposit button when the AF does'nt have any DS
=> #1356 - Add a constraint to avoid publishing AF not containing JDD

frontend/src/app/GN2CommonModule/form/taxa/taxa.component.ts
=> Fix frontend/taxa: display form contol value

frontend/src/app/components/nav-home/nav-home.component.html, frontend/src/app/components/nav-home/nav-home.component.scss, frontend/src/app/components/nav-home/nav-home.component.ts, frontend/src/assets/i18n/cn.json, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/fr.json
=> Refactor frontend/nav-home: use Material, simplify code

frontend/src/app/GN2CommonModule/GN2Common.module.ts, frontend/src/app/GN2CommonModule/pipe/strip-html.pipe.ts
=> Feat frontend/gn2common: add strip HTML Pipes

backend/geonature/core/users/register_post_actions.py
=> Fix frontend/users: use absolute URL in email

frontend/src/app/GN2CommonModule/form/date/date.component.ts
=> Fix frontend/pnx-date: display form contol value

backend/geonature/utils/command.py, frontend/src/app/app.module.ts, frontend/src/conf/app.config.ts.sample
=> Feat frontend/AppConfig: add possibility to use InjectionToken

frontend/src/app/GN2CommonModule/form/multiselect/multiselect.component.html, frontend/src/app/GN2CommonModule/form/multiselect/multiselect.component.ts
=> Fix frontend/multiselect: avoid duplicate selected item with Enter key

backend/geonature/utils/utilsmails.py
=> Fix backend/utilsmails: handle undefined recipients parameter

frontend/src/app/GN2CommonModule/GN2Common.module.ts, frontend/src/app/GN2CommonModule/service/cruved-store.service.ts, frontend/src/app/app.module.ts, frontend/src/app/components/auth/auth.service.ts
This avoid some race condition when cruved is used before the requests to get the cruved completes.
=> fetch cruved at app initialization

contrib/occtax/frontend/app/occtax-form/form-param/form-param.dialog.ts, contrib/occtax/frontend/app/occtax-form/map/map.component.ts, contrib/occtax/frontend/app/occtax-form/occurrence/occurrence.component.ts, contrib/occtax/frontend/app/occtax-form/releve/releve.component.ts
Parce que jamais deux sans trois.
Ajout de unsubscribe à différents Observable dans occtax pour éviter des sur-appels aux rechargements des components
=> Ajout de unsubscribe à différents Observable dans occtax

backend/geonature/utils/config_schema.py, config/geonature_config.toml.sample, docs/user-lecteur.md, docs/user_lecteur.md, frontend/src/app/components/login/login.component.html, frontend/src/app/components/login/login.component.ts
=> Acces grand public

frontend/src/app/GN2CommonModule/form/synthese-form/dynamycFormConfig.ts
=> Revert "filtre avancé "type d'information géographique""

frontend/src/app/metadataModule/af/af-card.component.html, frontend/src/app/metadataModule/af/af-card.component.scss, frontend/src/app/metadataModule/datasets/dataset-card.component.html, frontend/src/app/metadataModule/datasets/dataset-card.scss, frontend/src/app/metadataModule/metadata-dataset.component.html, frontend/src/app/metadataModule/metadata.component.html, frontend/src/app/metadataModule/metadata.component.scss
Ajout de l'info "Aucun acteur renseigné" si y'en a pas... 
En retour à #1404
=> Alerte acteur métadonnées

frontend/src/app/GN2CommonModule/service/cruved-store.service.ts, frontend/src/app/services/module.service.ts
=> Fix admin module loading

docs/admin-manual.rst
Rajout des commandes systemd / systemctl dans la doc pour les versions GeoNature 2.8+
=> Rajout systemd

frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.html, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.ts, frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html
=> Feat frontend/synthese: improve observation modal

backend/geonature/core/gn_synthese/routes.py, backend/geonature/core/gn_synthese/synthese_config.py, backend/geonature/core/gn_synthese/utils/query_select_sqla.py
=> Fix backend/synthese: improve precision and integer value generic fields

frontend/src/app/syntheseModule/synthese-results/synthese-list/modal-download/modal-download.component.html
=> Feat frontend/synthese: improve download/display limit modal

frontend/src/app/services/unauthorized.interceptor.ts
Pour répéter le bug de cookie disfonctionnel: 
sur chromium/chrome, setter le cookie:  par exemple window.cookieStore.set("token", "eytest")
=> Make sure redirection works

backend/geonature/core/gn_synthese/routes.py, backend/geonature/tests/fixtures.py, backend/geonature/tests/test_synthese.py
Ajout de tests des routes de la Synthèse
Corrections sur les tests déjà définis
=>  [Synthèse] Tests/synthese routes

frontend/src/app/components/home-content/home-content.component.html
Better display of homepage blocks on mobile.
=> Home layout - Responsive blocks

docs/installation-standalone.rst
=> Modification de l'ip_application 1 au lieu de 3

install/02_create_db.sh
Ajout des régions dans 02_install_db.sh
=> install db regions

frontend/src/app/GN2CommonModule/form/areas/areas.component.html, frontend/src/app/GN2CommonModule/form/areas/areas.component.ts, frontend/src/styles.scss
- Fix frontend/pnx-areas: improve component
- Feat frontend/ng-select: restore previous design for selected values
=> Frontend: improve pnx-areas component

contrib/gn_module_validation/frontend/app/components/validation-popup/validation-popup.component.html, contrib/gn_module_validation/frontend/app/components/validation-synthese-list/validation-synthese-list.component.html, contrib/gn_module_validation/frontend/app/components/validation-synthese-list/validation-synthese-list.component.scss, contrib/gn_module_validation/frontend/app/components/validation-synthese-list/validation-synthese-list.component.ts, contrib/gn_module_validation/frontend/app/components/validation.component.html, contrib/gn_module_validation/frontend/app/components/validation.component.ts, contrib/gn_module_validation/frontend/app/gnModule.module.ts, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.ts, frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html, frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts, frontend/src/app/shared/syntheseSharedModule/synthese-shared.module.ts, frontend/src/app/syntheseModule/synthese.component.ts, frontend/src/assets/i18n/fr.json
> Cette contribution a été réalisée selon les besoins de [picardie-nature](http://www.picardie-nature.org/) et en accord avec les principes de la communauté GeoNature #1727 
Cette PR permet de partager une occurence via le détail consulté dans le module VALIDATION ou SYNTHESE.
Les modifications suivantes ont été apportées.
* Ajout d'un bouton dans la toolbar d'actions
* i18n
* Mise en forme avec VSCode (à la sauvegarde selon les bonnes pratiques de la doc GeoNature)
* Utilisation [cdkCopyToClipboard](https://v12.material.angular.io/cdk/clipboard/overview) pour le copier/coller
* Ajout d'une route [occurrence/:id_synthese](https://github.com/picardie-nature/GeoNature/commit/2d48c20d3c30a38bfca64a97ed1629d0c8609aae#diff-327ecaf8cb4cee506d54909e857c6d36058c5086b1e2942b4154f8875ab939c3) pour …
=> Partage d'une occurrence via un permalien

frontend/src/app/GN2CommonModule/form/data-form.service.ts, frontend/src/app/GN2CommonModule/form/nomenclature/nomenclature.component.ts
Possibilité de filtrer les items de nomenclatures par "cd_nomenclature".
On passe la liste des cd_nomenclature que l'on souhaite
Filtre effectué côté backend
=> add cdNomenclatures input to filter with nomenclature

install/01_install_backend.sh
Ajout de applicaiton_name dans SQLALCHEMY_DATABASE_URI dans les scripts d'installation
=> feat/application_name 01_install_backend

backend/geonature/tests/fixtures.py, backend/geonature/tests/test_gn_meta.py, backend/geonature/tests/test_gn_profiles.py, backend/geonature/tests/test_synthese.py
- Test backend/synthese: fix observation_count_per_column
- Test backend/meta: skip uuid report if too much observations
- Test backend/fixture: use config param for geom coordinates
- Test backend/profiles: use synthese ids in higher range
=> Fix backend/tests : improve testing with real data

frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.scss, frontend/src/app/GN2CommonModule/form/taxonomy/taxonomy.component.scss
=> Feat: show dropdown above everything, reduce font size

frontend/src/app/GN2CommonModule/form/areas/areas.component.html, frontend/src/app/GN2CommonModule/form/areas/areas.component.ts
Add the ability to get items from the current selection. Useful to get area_name field value.
=> Feat: add output to pnx-areas

contrib/gn_module_validation/frontend/app/components/validation-modal-info-obs/validation-modal-info-obs.component.html, frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html, frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts, frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.ts, frontend/src/app/syntheseModule/synthese.component.ts, frontend/src/app/syntheseModule/synthese.module.ts
PR pour que le permalien de la synthese redirige vers la synthese et non le module de validation
=> Permalien dans la synthese

backend/geonature/core/gn_synthese/routes.py, backend/geonature/core/gn_synthese/utils/blurring.py, backend/geonature/core/gn_synthese/utils/query_select_sqla.py, backend/geonature/utils/config_schema.py, config/default_config.toml.example, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.service.ts, frontend/src/app/GN2CommonModule/map-list/map-list.component.ts, frontend/src/app/GN2CommonModule/map-list/map-list.service.ts, frontend/src/app/GN2CommonModule/map/filelayer/filelayer.component.ts, frontend/src/app/GN2CommonModule/map/map.component.scss, frontend/src/app/components/home-content/home-content.component.ts, frontend/src/app/syntheseModule/synthese-results/synthese-carte/synthese-carte.component.scss, frontend/src/app/syntheseModule/synthese-results/synthese-carte/synthese-carte.component.ts, frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.ts, frontend/src/app/syntheseModule/synthese.component.html, frontend/src/app/syntheseModule/synthese.component.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/fr.json
=> Feat: add areas view for synthese

frontend/src/app/app.module.ts, frontend/src/app/components/nav-home/nav-home.component.html, frontend/src/app/routing/app-routing.module.ts.sample, frontend/src/app/routing/routes-guards.service.ts
=> Fix public access: remove profil menu for public access

backend/requirements-common.in, backend/requirements-dev.txt, backend/requirements.txt
There is no reason to stay with celery 4 as we upgraded to flask 2
=> requirements: upgrade to celery 5

backend/geonature/core/command/main.py, backend/geonature/utils/command.py, docs/admin-manual.rst, docs/development.rst
Please use npm directly:
cd frontend
nvm use
npm run start
=> delete dev_front sub-command

.github/workflows/cypress.yml, backend/geonature/core/gn_meta/models.py, backend/geonature/core/gn_meta/routes.py, backend/geonature/tests/fixtures.py, backend/geonature/tests/test_gn_meta.py, contrib/occtax/backend/occtax/migrations/data/sample_data_test.sql, frontend/angular.json, frontend/cypress/integration/metadata-spec.js, frontend/cypress/integration/synthese-spec.js, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.html, frontend/src/app/metadataModule/af/af-card.component.html, frontend/src/app/metadataModule/af/af-form.component.html, frontend/src/app/metadataModule/datasets/dataset-form.component.html, frontend/src/app/metadataModule/metadata-dataset.component.html, frontend/src/app/metadataModule/metadata.component.html, frontend/src/app/metadataModule/metadata.component.scss, frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html, frontend/src/app/syntheseModule/synthese-results/synthese-list/modal-download/modal-download.component.html, frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.html
=> fix frontend tests

backend/geonature/utils/config_schema.py
Default OpenStreetMap was not complete.
=> Improve default OSM attributions

frontend/src/app/syntheseModule/synthese.component.html, frontend/src/styles.scss
Ajout d'un message optionnel lors du chargement des données dans la synthèse
=> Ajout message lors du chargement des données dans la synthèse

frontend/src/app/components/home-content/home-content.component.html
=> Feat frontend/home-content: format global stats numbers

backend/geonature/core/admin/admin.py, backend/geonature/templates/admin/index.html, backend/geonature/templates/admin/index_layout.html, backend/geonature/templates/layout.html
Modernisation de l'interface d'admin  
- passage à bootstrap 4 (et fontawesome en conséquence)
- Mise du menu dans une sidebar présente sur toute les pages
=> Put sidebar with menu in layout

docs/admin-manual.rst
Bring back Occtax-dataset (module duplication) documentation which was lost when reorganizing PR and merges.
=> Bring back Occtax dataset documentation #621

docs/admin-manual.rst
Maj de la doc sur la duplication d'occtax
=> Hotfix doc

backend/geonature/core/users/routes.py
=> fix validation of newly registered users

install/install_all/install_all.sh
[Ref #215](https://github.com/PnX-SI/GeoNature/issues/2125)
Le package xvfb  est une dépendance qui semble manquante (voir issue).
=> 2125 Debian pkg xvfb - Cypress requirement

backend/geonature/core/gn_commons/routes.py
This reverts commit 9c7a34dca8bfff86952355c41ab6f71657281a06.
=> Revert "modules: list related datasets"

backend/geonature/app.py, backend/geonature/core/gn_meta/repositories.py, backend/geonature/core/gn_meta/routes.py, backend/geonature/core/gn_permissions/backoffice/views.py, backend/geonature/core/gn_permissions/decorators.py, backend/geonature/core/gn_permissions/tools.py, backend/geonature/core/routes.py, backend/geonature/core/users/routes.py, backend/geonature/core/utils.py, backend/geonature/tests/test_gn_permission.py, contrib/gn_module_occhab/backend/gn_module_occhab/blueprint.py
Voir https://github.com/PnX-SI/GeoNature/issues/2162
Il s’agit ici uniquement de supprimer son usage dans le cœur de GeoNature, tout en rajoutant un warning de dépréciation pour les modules l’utilisant encore potentiellement.
=> Suppression de get_role dans check_cruved_scope

.github/workflows/pytest.yml, backend/geonature/core/gn_meta/models.py, backend/geonature/core/gn_meta/repositories.py, backend/geonature/core/gn_meta/routes.py, backend/geonature/core/gn_permissions/backoffice/views.py, backend/geonature/core/gn_permissions/decorators.py, backend/geonature/core/gn_synthese/models.py, backend/geonature/core/routes.py, backend/geonature/core/sensitivity/routes.py, backend/geonature/core/sensitivity/utils.py, backend/geonature/core/users/routes.py, backend/geonature/core/utils.py, backend/geonature/migrations/versions/2d7edda45dd4_sensitivity_fk_on_delete.py, backend/geonature/tests/test_gn_meta.py, backend/geonature/tests/test_sensitivity.py, contrib/gn_module_occhab/backend/gn_module_occhab/blueprint.py, frontend/src/app/metadataModule/metadata.component.ts, frontend/src/app/metadataModule/services/metadata.service.ts, install/03_create_db.sh
=> Filtrer les métadonnées par zonage

backend/geonature/core/notifications/routes.py, backend/geonature/core/notifications/utils.py, backend/geonature/migrations/versions/36d0bd313a47_add_notification_schema_tables_and_data.py, backend/geonature/tests/test_notifications.py, config/default_config.toml.example, contrib/gn_module_validation/backend/gn_module_validation/blueprint.py, frontend/src/app/components/nav-home/nav-home.component.html, frontend/src/app/components/nav-home/nav-home.component.ts
- Notification dans l'application au lieu de en base de données
- Notification actif par default
- Pas de numéro sur l'icone de notification quand 0 notification
- Dans le module de validation la notification pointe vers l'url de la synthèse et pas de la validation
=> Update with Camille change request

.github/workflows/cypress.yml, backend/geonature/core/ref_geo/routes.py, backend/geonature/tests/test_ref_geo.py, backend/geonature/utils/config_schema.py, config/default_config.toml.example, config/test_config.toml, frontend/cypress/fixtures/config.json, frontend/cypress/integration/control-layers-spec.js, frontend/src/app/GN2CommonModule/map/map.component.ts, frontend/src/app/GN2CommonModule/map/map.service.ts
=> [carto] Afficher les zonages du ref_geo

backend/geonature/utils/config_schema.py
> Ref #2208 
> PR financé par MNHN / PatriNat
Cette PR modifie l'opacité par défaut pour la couche ZNIEFF1.
=> #2208/Default ZNIEFF1 REF_LAYERS opacity

frontend/src/app/components/auth/auth.service.ts, frontend/src/app/routing/auth-guard.service.ts
Duplicates PR #1653, and fixes issue #1650
=> accès public via url access=public

docs/CHANGELOG.md, docs/admin-manual.rst
https://github.com/PnX-SI/GeoNature/issues/2202
=> Updated docs and changelog, for public access modifications

backend/geonature/core/notifications/utils.py, backend/geonature/tests/test_notifications.py, backend/geonature/utils/config_schema.py, config/default_config.toml.example, config/geonature_config.toml.sample, frontend/src/app/components/nav-home/nav-home.component.html, frontend/src/app/components/nav-home/nav-home.component.ts
This remplace notification block with standalone enable parameter.
=> config: add notifications_enabled parameter

backend/geonature/core/gn_meta/models.py, backend/geonature/core/gn_meta/schemas.py, backend/geonature/utils/schema.py
- Use ``__module_code__`` & ``__object_code__`` to automatically retrive permissions
- Require ``has_instance_permission`` to be defined on model to convert scope to bool
=> CruvedSchemaMixin without required context

contrib/occtax/backend/occtax/migrations/87705981de5e_occtax_samples_with_id_module.py, contrib/occtax/backend/occtax/migrations/cce08a64eb4f_insert_occtax_sample_data.py, install/migration/migration.sh
This ensure support for db with cce08a64eb4f but without 023b0be41829 yet.
=> fix occtax samples: move id_module dep in new rev

frontend/src/app/components/home-content/home-content.component.html, frontend/src/app/components/home-content/home-content.component.ts, frontend/src/app/syntheseModule/synthese-results/synthese-carte/synthese-carte.component.ts
=> Fix: use correct color for meshes and only cluster in home map 

install/06_configure_apache.sh, install/assets/geonature_apache.conf
=> enable apache gzip compression on api

docs/https.rst
=> Update HTTPS doc

backend/geonature/core/command/create_gn_module.py
``geonature install-gn-module ~/mon_module``
Plus besoin de fournir le module code.
Le module code en argument est encore supporté à des fins de rétro-compatibilité.
=> install-gn-module: autodetect module code

frontend/src/app/components/nav-home/nav-home.component.ts
=> fix(front): remove notification count call on init

backend/geonature/utils/config_schema.py, config/geonature_config.toml.sample
Mon lint n'est pas bon...
Mais j'ai fait ça depuis Github 😇
=> Add default introduction text

contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.html, contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
=> releveList : reprise affichage info digitiser

backend/geonature/core/gn_meta/models.py, backend/geonature/core/gn_meta/routes.py
Ajout du `joinedload` et de `acquisition_framework` afin de pouvoir calculer les droits
Closes #2454
=> [Metadonnées] Fix/datasets digitizer

backend/geonature/migrations/versions/cf1c1fdbde77_correction_sql_on_delete_module.py
https://github.com/PnX-SI/GeoNature/issues/2449
=> Correction de la FK permissions / module

backend/geonature/core/gn_permissions/backoffice/views.py
=> fix(access backoffice permissions) set module "ADMIN" and object "PERMISSIONS"

backend/geonature/core/command/create_gn_module.py
=> fix(install-gn-module): load modules if necessary

contrib/gn_module_occhab/backend/gn_module_occhab/blueprint.py
=> occhab: order station by date_min.desc()

frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.html, frontend/src/app/syntheseModule/synthese.component.html
fix https://github.com/PnX-SI/GeoNature/issues/2470
=> fix validation filtre avance ref #2470

backend/geonature/core/command/create_gn_module.py, docs/CHANGELOG.md
Fix https://github.com/PnX-SI/gn_module_export/issues/128
=> `install-gn-module`: reload config

backend/geonature/core/gn_synthese/routes.py, backend/geonature/core/gn_synthese/utils/query_select_sqla.py, backend/geonature/tests/test_synthese.py, docs/CHANGELOG.md, frontend/src/app/GN2CommonModule/form/synthese-form/dynamicFormConfig.ts
Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité île de France, ajout d'un nouveau filtre avancé : **Est commenté**.
Ce filtre fonctionne de la même façon que les filtres "Est épinglé" et "Est signalé".
=> feat(dynamicForm): add has_comment custom filter

contrib/occtax/backend/occtax/migrations/22c2851bc387_add_database_default_value.py
Petite correction d'un SET qui générait des erreurs pendant le downgrade
=> fix occtax downgrade in 22c2851bc387 migration

backend/geonature/core/gn_synthese/utils/query_select_sqla.py, backend/geonature/tests/test_synthese.py, contrib/gn_module_validation/frontend/app/components/validation-synthese-carte/validation-synthese-carte.component.ts, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.service.ts, frontend/src/app/syntheseModule/services/form.service.ts, frontend/src/app/syntheseModule/synthese-results/synthese-carte/synthese-carte.component.ts
=> fix synthese geoIntersection research

backend/geonature/core/gn_permissions/backoffice/views.py
=> permissions backoffice: fix perf issue

backend/geonature/core/admin/__init__.py, backend/geonature/core/gn_commons/admin.py, backend/geonature/core/gn_commons/models/additional_fields.py, backend/geonature/core/gn_commons/models/base.py, backend/geonature/core/gn_commons/routes.py, backend/geonature/core/gn_permissions/admin.py, backend/geonature/core/gn_permissions/models.py, backend/geonature/core/gn_permissions/tools.py, backend/geonature/migrations/versions/7fe46b0e4729_multiple_filters_per_permission.py, backend/geonature/tests/fixtures.py, backend/geonature/tests/test_gn_commons.py, backend/geonature/tests/test_gn_meta.py, backend/geonature/tests/test_permissions.py
=> permissions: multiple filters per permission

backend/geonature/core/admin/utils.py, backend/geonature/core/gn_permissions/admin.py, backend/geonature/core/gn_permissions/models.py, backend/geonature/migrations/versions/f051b88a57fd_permissions_available.py
And so, for each (module, object, action).
Thus, indicates if scope filter is supported.
TODO: déclaration des permissions des modules du cœur
=> declaration of available permissions

install/assets/maintenance.html, install/assets/vhost_apache_maintenance.conf, install/install_all/install_all.sh
See https://github.com/PnX-SI/GeoNature/pull/2526#issuecomment-1533364195
=> Install_all - Copy maintenance HTML page

backend/geonature/core/gn_meta/mtd/mtd_utils.py
Regression : was removed in 357227ee260967ee1454f3828f60a67cf939b68b.
=> fix(mtd: sync) Add back automatic association dataset-modules on mtd sync

backend/geonature/app.py
This make ``APPLICATION_ROOT`` works with dev mode.
=> handle APPLICATION_ROOT with DispatcherMiddleware

docs/CHANGELOG.md, frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.html, frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.ts
=> fix checkbox ref #2518

backend/geonature/core/gn_permissions/admin.py
- Ajout de filtre libre sur identifiant + nom complet sur les utilisateurs et les groupes
- ajout filtre par module sur les permissions disponibles
voir #2572
=> Ajout de filtres sur l'admin des permssions

docs/admin-manual.rst
Replace "taxonomie.bdc_statut_texte" with "taxonomie.bdc_statut_text".
=> Orthographic correction in docs: "taxonomie.bdc_statut_text"

.github/workflows/cypress.yml, backend/geonature/core/gn_permissions/commands.py, contrib/occtax/backend/occtax/migrations/data/sample_data_test.sql, install/03_create_db.sh, install/04_install_gn_modules.sh
This flag is use for installation script
=> Add --yes flag to skip prompt on supergrant command

backend/geonature/core/gn_synthese/utils/query_select_sqla.py, backend/geonature/tests/test_synthese.py, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.html
Voir https://github.com/PnX-SI/GeoNature/issues/2568
Superset : https://github.com/PnX-SI/GeoNature/pull/2569
=> feat: Unaccent on observers filter

backend/geonature/core/gn_synthese/routes.py, backend/geonature/tests/fixtures.py, backend/geonature/tests/test_gn_meta.py, backend/geonature/tests/test_sensitivity.py, backend/geonature/tests/test_synthese.py
=> feat(permissions): use new permissions in synthese exports

backend/static/css/metadata_pdf.css, frontend/src/app/metadataModule/af/af-card.component.html, frontend/src/app/metadataModule/af/af-card.component.ts
- go to metadata
- go to a CA With a JDD
- go to informations and see that the chart shows with correct data
- press export pdf and see that the chart shows on the pdf with correct data
=> fix(CA): fix the chart and the pdf

backend/geonature/utils/config_schema.py
Pour traiter les cas ou l'on a une chaine de caractere avec plusieurs validateurs
=> fix validator_mail schema

backend/geonature/migrations/versions/95acee9f0452_add_comment_notification.py
Set comment notification active for all users by default
https://github.com/PnX-SI/GeoNature/issues/2460#issuecomment-1504873866
=> feat(notification): set notification by default

frontend/src/app/syntheseModule/synthese-results/synthese-carte/synthese-carte.component.ts
=> fix synthese: resolve multipoint error

docs/user-manual.rst
Rédaction/Illustration de la documentation utilisateurs pour le module métadonnées
(images fournies par ailleurs pour hébergement sur le serveur de geonature.fr)
=> Documentation utilisateur du module métadonnées

docs/user-manual.rst
=> User-manual / Add Admin permission section #2605

.github/ISSUE_TEMPLATE/rapport-de-bug.md
=> [GitHub] Correction d'une faute d'orthographe dans le template d'issue

backend/geonature/app.py
This allows custom static files to work with an APPLICATION_ROOT.
=> move DispatcherMiddleware after custom /static

frontend/src/app/metadataModule/af/af-card.component.html
Ajout de la description du cadre d'acquisition dans la fiche
Closes #2716
=> fix(meta): missing description in af

backend/geonature/core/gn_commons/routes.py, backend/geonature/core/gn_synthese/routes.py, backend/geonature/tests/test_mtd.py, backend/geonature/tests/test_synthese.py
PR to fix errors provoked by the 2.13.4 merge into develop.
=> Fix/error of 2.13.4 merge into develop

frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.html, frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.ts
This PR is a duplicate of #2801 due to merge/rebase issues... 
All modifications are credited to @Pierre-Narcisi
=> fix(synthese) fixing sort in synthese V2

backend/geonature/core/gn_permissions/admin.py
L’admin étant toujours basé sur les query, il faut les garder.
=> admin: fix regression related to sqlachemy 2

frontend/src/app/metadataModule/af/af-card.component.html, frontend/src/app/metadataModule/datasets/dataset-card.component.html
ajout type financement dans métadonnées.
Page CA et JDD
=> ajout type financement

.github/workflows/cypress.yml, docs/_static/architecture_globale.drawio, frontend/cypress/e2e/metadata-spec.js
=> Add new diagram in the documentation

backend/geonature/core/imports/templates/import_template_pdf.html
Use data.statistics (no more data.taxa_account)
Change the way to display statistic according to
different stats from different entity
Example with fake data.statistics :
=> [IMPORT] feat: remove taxa_count and add stats in report

backend/geonature/core/gn_commons/routes.py, backend/geonature/core/imports/models.py, contrib/gn_module_occhab/frontend/app/components/occhab-map-list/occhab-map-list.component.html, contrib/gn_module_occhab/frontend/app/components/occhab-map-list/occhab-map-list.component.scss, contrib/gn_module_occhab/frontend/app/components/occhab-map-list/occhab-map-list.component.ts, frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.html, frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.scss, frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/fr.json
Tâches liées : https://github.com/orgs/PnX-SI/projects/13/views/6?pane=issue&itemId=50176514 et https://github.com/orgs/PnX-SI/projects/13/views/6?pane=issue&itemId=50176614
Résumé :
=> [IMPORT] Feat/front add btn import data in module

backend/geonature/core/imports/checks/sql/core.py
=> [IMPORT] feat(checks) manage multi in checks

backend/geonature/core/gn_synthese/module.py, backend/geonature/core/imports/models.py, contrib/gn_module_occhab/backend/gn_module_occhab/module.py, frontend/src/app/metadataModule/datasets/dataset-card.component.html, frontend/src/app/modules/imports/components/import_process/upload-file-step/upload-file-step.component.ts
In this task, i fixed the import button in metadata, and the buttons on the sources at the bottom on the dataset page
=> [IMPORT] Feat/metadata import button

backend/geonature/tests/imports/files/synthese/multiline_comment_file.csv, backend/geonature/tests/imports/test_imports_synthese.py, backend/geonature/tests/imports/utils.py
Add test to check if t_import.erroneous_rows are equals to lines error in csv
=> [IMPORT][BACKEND] Add test for line number errors

backend/geonature/core/imports/checks/dataframe/utils.py, backend/geonature/core/imports/checks/sql/utils.py, backend/geonature/core/imports/models.py, backend/geonature/core/imports/routes/imports.py, backend/geonature/core/imports/templates/import_template_pdf.html, backend/geonature/migrations/versions/imports/bfc90691737d_add_id_entity_in_users_errors.py, backend/geonature/tests/imports/jsonschema_definitions.py, backend/geonature/tests/imports/test_imports_occhab.py, backend/geonature/tests/imports/test_imports_synthese.py, backend/geonature/tests/imports/utils.py, frontend/src/app/modules/imports/components/import_errors/import_errors.component.html, frontend/src/app/modules/imports/components/import_report/import_report.component.html, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/fr.json
Closes [Issue](https://github.com/orgs/PnX-SI/projects/13/views/6?pane=issue&itemId=50175164)
[Périmètre] Erreur d'import
Ce travail ajoute l'entité concernée à l'erreur détectée à l'import. 
Le model d'erreur est enrichie d'une fk entité.
Les afficahges et pdf sont enrichis de cette information.
Certaines routes sont mises à jour pour inclure cette information.
=> [IMPORT] [ERRORS] Add entity in import error

docs/CHANGELOG.md, docs/authors.rst
Première trame du changelog de la version 2.14.0
=> Changelog 2.14

contrib/gn_module_validation/frontend/app/components/validation-modal-info-obs/validation-modal-info-obs.component.html
Replace "comentaire" by "commentaire"
=> Correction of validation modal text

docs/FAQ.rst, docs/installation-standalone.rst, frontend/src/assets/config.sample.json, install/05_install_frontend.sh
https://github.com/PnX-SI/GeoNature/issues/2936
=> Remove `http:` prefix in frontend `config.json` file

docs/development.rst
Documentation rapide pour le lint html
=> feat (doc) add doc

frontend/src/app/GN2CommonModule/form/acquisition-frameworks/acquisition-frameworks.component.ts, frontend/src/app/GN2CommonModule/form/areas/areas.component.ts, frontend/src/app/GN2CommonModule/form/datalist/datalist.component.ts, frontend/src/app/GN2CommonModule/form/datasets/datasets.component.ts, frontend/src/app/GN2CommonModule/form/nomenclature/nomenclature.component.ts, frontend/src/app/GN2CommonModule/form/observers-text/observers-text.component.ts, frontend/src/app/GN2CommonModule/form/observers/observers.component.ts
Fix : https://github.com/PnX-SI/GeoNature/issues/2961
=> fix GenericFormComponent inheritance - fix #2961

backend/geonature/core/gn_synthese/utils/query_select_sqla.py
Grosse PR pour corriger la route /validation en Post qui plante si on a un scope de 1 ou 2.
=> [Validation] correction de la récupération des Datasets en scope 1 ou 2

frontend/src/app/modules/imports/components/import_list/import-list.component.ts
=> [IMPORT] Generic labeling for tooltip statistics in the import list

backend/geonature/core/imports/config_schema.py, config/default_config.toml.example, frontend/src/app/modules/imports/components/import_report/import_report.component.ts
This PR propose a feature to allow the user to customize the import report pdf filename.
=> [IMPORT] Custom Report PDF filename + Add import configuration in `defaut_config.toml`

frontend/src/app/modules/imports/components/import_process/fields-mapping-step/fields-mapping-step.component.html, frontend/src/app/modules/imports/components/import_process/fields-mapping-step/fields-mapping-step.component.ts
Les modéles sont sort par ordre alphabetique et maintenant c'est un ng-select
=> [IMPORT] [FRONTEND] Feat(mapping) sort mapping and put a ng-select

frontend/src/app/modules/imports/components/import_process/content-mapping-step/content-mapping-step.component.html, frontend/src/app/modules/imports/components/import_process/content-mapping-step/content-mapping-step.component.ts, frontend/src/assets/i18n/fr.json
Skipping the content mapping step if no nomenclatures to map
=> [IMPORT] Feat/skip nomenclature

backend/geonature/core/gn_synthese/imports/__init__.py, backend/geonature/core/gn_synthese/module.py, backend/geonature/core/imports/models.py, backend/geonature/core/imports/routes/imports.py, backend/requirements-common.in, frontend/angular.json, frontend/package-lock.json, frontend/package.json, frontend/src/app/modules/imports/components/import_report/import_report.component.html, frontend/src/app/modules/imports/components/import_report/import_report.component.ts, frontend/src/app/modules/imports/services/data.service.ts, frontend/src/app/typings/bokeh.d.ts
This PR propose a way to make import report generic. See #2996 for more details
Preview :  
[Capture vidéo du 24-04-2024 17:36:29.webm](https://github.com/PnX-SI/GeoNature/assets/4259846/a2bfbaec-9590-4632-a44a-d0bb0a691e1f)
=> [IMPORT V3][GEONATURE] Graphique générique dans le rapport de l'import

backend/geonature/core/gn_synthese/imports/__init__.py, backend/geonature/core/imports/templates/import_template_pdf.html, backend/geonature/core/imports/utils.py, frontend/src/app/modules/imports/components/import_report/import_report.component.html
This PR propose to replace the barplot by a pie chart in the import report of the synthese destination.
[Capture vidéo du 30-04-2024 16:17:03.webm](https://github.com/PnX-SI/GeoNature/assets/4259846/257ead7f-fe03-41ad-93b2-96f4d13048c2)
=> [IMPORTV3][SYNTHESE] Replace barplot by a piechart in the import report

backend/geonature/core/imports/routes/imports.py, backend/geonature/core/imports/templates/import_template_pdf.html, backend/static/css/metadata_pdf.css, frontend/src/app/modules/imports/components/import_report/import_report.component.html, frontend/src/app/modules/imports/components/import_report/import_report.component.ts, frontend/src/app/modules/imports/services/data.service.ts
Quelques petits changements: 
- fix de la taille du spinner dans le bouton d'export
- report.html: fix de la structure html, et lint du fichier d'export 
- report.html: simplification du layout général et du css
- amélioration de l'export des chart: chore sur les noms des functions, variables, génération d'image
- fix du problème de sync entre la génération des charts et la génération du PDF
=> [IMPORT][PDF REPORT] Rework some part of the PDF generation

contrib/gn_module_occhab/backend/gn_module_occhab/imports/plot.py, contrib/gn_module_occhab/backend/gn_module_occhab/module.py
This PR is a duplicate of #3014. Due to an historic issue, this PR was created.
=> [IMPORTV3] Add occhab report plot

backend/geonature/app.py, backend/geonature/tasks/__init__.py, backend/geonature/utils/celery.py
This PR aims to fix issue with closing SQLAlchemy session started by flask-sqlalchemy+celery. Check issue #3050 for more details.
This PR was co-authored with @TheoLechemia.
closes #3050
=> [CELERY] fix/sqla session closing

frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html, frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts
https://github.com/PnX-SI/GeoNature/issues/3086
=> fix(synthse) actors display

docs/admin-manual.rst
Fix table and function name in `gn_profiles` schema
=> [doc] Fix table and fn name

backend/geonature/core/gn_commons/routes.py, frontend/src/app/components/sidenav-items/sidenav-items.component.html, frontend/src/app/models/module.model.ts
This PR propose to fix the redirection to external module in the GeoNature menu.
closes #3093
=> [MAINTENANCE] External module in menu

backend/geonature/core/gn_synthese/imports/mixins.py, backend/geonature/core/imports/config_schema.py
See https://github.com/PnX-SI/gn_module_import/issues/459
=> fix(import): per dataset uuid check

backend/geonature/core/imports/models.py, backend/geonature/tests/imports/test_imports_occhab.py, contrib/gn_module_occhab/backend/gn_module_occhab/imports/mixins.py, contrib/gn_module_occhab/backend/gn_module_occhab/models.py
=> [IMPORT] Safe deletion of muli-entities import

backend/geonature/core/imports/checks/sql/extra.py
This PR adapt `check_cd_nom` to model changes that will happen in next version of TAXHUB (V2)
=> Adapt check_cd_nom to taxhub v2 model changes

.github/workflows/pytest.yml
The token is unreadable for PR from fork…
=> codecov action: remove token

frontend/cypress/e2e/import/step3-field-mapping-spec.js, frontend/cypress/e2e/import/step4-content-mapping-spec.js, frontend/src/app/GN2CommonModule/form/form.service.ts, frontend/src/app/modules/imports/components/import_report/import_report.component.html, frontend/src/app/modules/imports/services/mappings/field-mapping.service.ts
Les tests frontend ne passaient plus sur feat/import, un problème dans le mapping, ça devrait passer maintenant
=> Fix(mapping) fix mapping

backend/geonature/core/taxonomie/admin.py
=> fix (taxhub) : missing plural in an object code declaration in admin view

backend/geonature/core/sensitivity/routes.py
=> fix(sensitivity) : debug command `geonature sensitivity info`

backend/requirements-dev.txt
Mise à jour du sous module TaxHub avec le dernier commit de la branche develop. Cela nécessite une correction dans les dépendances en raison d’une évolution côté TaxHub.
=> bump TaxHub

backend/geonature/migrations/versions/imports/2b0b3bd0248c_multidest.py
This PR is a duplicate of #3126.
=> [IMPORT] Migration adjustement for import v3

docs/installation.rst
https://github.com/PnX-SI/GeoNature/issues/3112
=> Install doc update

frontend/angular.json, frontend/package-lock.json, frontend/package.json, frontend/src/app/metadataModule/datasets/dataset-card.component.html, frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html, frontend/src/index.html, frontend/src/styles.scss
Ajout des googles symbols pour pouvoir ajouter le pin dans la fiche info d'une obs
=> add material symbols

backend/geonature/core/gn_meta/routes.py, backend/geonature/tests/fixtures.py, backend/geonature/tests/test_gn_meta.py, backend/geonature/tests/test_synthese.py
resolves #3228 
Include the correction of the test of the acquisition frameworks' statistics route
=> fix(metadata): fix count of distinct taxon in the af page

backend/geonature/core/gn_meta/models/aframework.py, backend/geonature/core/gn_meta/models/commons.py, backend/geonature/core/gn_meta/models/datasets.py, backend/geonature/tests/test_gn_meta.py, docs/CHANGELOG.md, frontend/src/app/metadataModule/metadata.component.ts, frontend/src/app/metadataModule/services/metadata.service.ts
This PR adds changes to #3295.
=> Amélioration de la recherche des métadonnées + ajouts

backend/geonature/core/gn_meta/models/datasets.py, backend/geonature/core/gn_synthese/models.py
With the help of @TheoLechemia @edelclaux  and @andriacap ;)
In VSCode, you can add the following in a launch.json in the `.vscode` directory :
```json
{
"version": "0.2.0",
"configurations": [
{
"name": "GeoNature Backend Debug",
"type": "python",
"request": "launch",
"cwd": "${workspaceFolder}/backend/geonature",
"python": "${workspaceFolder}/backend/venv/bin/python3",
"module": "flask",
"env": {
"FLASK_APP": "app.py",
"FLASK_DEBUG": "1",
"FLASK_ENVIRONMENT": "development",
"FLASK_SQLALCHEMY_DB": "geonature.utils.env.db"
},
"args": ["run", "--port", "8000", "--reload"],
"justMyCode": false
}
]
}
```
=> Fix model to enable debug mode

backend/geonature/core/gn_synthese/utils/query_select_sqla.py
=> fix(synthese): fix bdc status filter with blurring permissions

backend/geonature/core/command/main.py
Suite à un bug sur les instances qui récupère toutes leur données depuis la plateforme Métadonnée de l'INPN, proposition de commande de management permettant de supprimer des métadonnées injustement récupérées.
=> feat(mtd): added a managment command to delete wrong mtd on INPN only instance

frontend/src/app/metadataModule/metadata.component.html
Quick fix #3365 for GINCO 2.14
=> fix(MTD): changed tooltip of refresh research so it describe what is currently doing

backend/geonature/core/gn_synthese/utils/blurring.py, backend/geonature/core/gn_synthese/utils/query_select_sqla.py
Continue the work started in #3325
=> fix(synthese) :Fix area filter

backend/geonature/migrations/versions/54e5b4a96add_modifiy_validation_status_trigger.py
=> feat (synthese): update meta_validation_date in the synthese when new validation

backend/geonature/utils/config_schema.py, config/default_config.toml.example, contrib/gn_module_validation/backend/gn_module_validation/blueprint.py, frontend/cypress/e2e/homepage-spec.js, frontend/src/app/GN2CommonModule/others/badge/badge.component.scss, frontend/src/app/GN2CommonModule/others/badge/badge.component.ts, frontend/src/app/app.module.ts, frontend/src/app/components/home-content/home-content.component.html, frontend/src/app/components/home-content/home-content.component.ts, frontend/src/app/components/home-content/home-discussions/home-discussions-table/home-discussions-table.component.ts, frontend/src/app/components/home-content/home-discussions/home-discussions.component.ts, frontend/src/app/components/home-content/home-discussions/home-discussions.service.ts, frontend/src/app/components/home-content/home-validations/home-validations.component.html, frontend/src/app/components/home-content/home-validations/home-validations.component.scss, frontend/src/app/components/home-content/home-validations/home-validations.component.ts, frontend/src/app/components/home-content/home-validations/home-validations.service.ts
Closes #3226 
L'issue est assez détaillée, et discutée.
N'hésitez pas à me contacter si besoin de plus de précisions !
=> Feat: Dernières validations

frontend/src/app/modules/imports/components/import_process/content-mapping-step/content-mapping-step.component.ts
=> feat(monitoring): default mapping now reload when selecting it back

backend/geonature/utils/config_schema.py, config/default_config.toml.example
=> Feat: Add  SQLAlchemy engine configuration parameter

backend/geonature/core/gn_meta/models/aframework.py, backend/geonature/core/gn_meta/models/datasets.py, backend/geonature/migrations/versions/26a5d314b886_add_additional_data_field_on_gn_meta_.py, frontend/angular.json
Ajout des champs JSONB `additional_data` sur les tables `gn_meta.t_datasets` et `gn_meta.t_acquisition_frameworks` (cf. #2745)
=> [METADATA] Ajout des champs additional_data pour les JDD et AF

contrib/gn_module_validation/backend/gn_module_validation/blueprint.py
The validation homepage was loading all the observations, which was causing a crash in most cases!
=> Fix validation performance

backend/geonature/core/gn_synthese/blueprints/exports.py
=> fix synthese export by adding distinct

.gitignore
=> remove config.py entry in the .gitignore

frontend/angular.json
=> Fix output of external modules assets

backend/geonature/core/gn_synthese/imports/plot.py, frontend/src/app/modules/imports/components/import_report/import_report.component.ts
=> fix (import) : debug report pdf generation

backend/geonature/core/gn_meta/routes.py
https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/pull/56
Première utilisation dans le module méta-données
=> Utilisation de ordered

frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts
getReport was not calling the right route
=> Fix(reports) call good route

backend/geonature/migrations/versions/imports/a11c9a2db7bb_set_import_module_type.py, contrib/occtax/frontend/app/occtax-map-list/filter/occtax-map-list-filter.component.html, frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.html, frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.ts, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.html, frontend/src/app/GN2CommonModule/map/map.service.ts, frontend/src/app/modules/imports/components/import_list/import-list.component.html, frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-list.component.html, frontend/src/app/syntheseModule/taxon-sheet/tab-observations/tab-observations.component.html
This PR integrates last corrections in order to release the 2.16.0 version of GeoNature.
=> Release 2.16.0 - Last fixes

.pre-commit-config.yaml
This PR propose to extend the `pre-commit-config.yaml` with:
- prettier linting
- commit and branch naming
=> Feature: update pre-commit

frontend/src/app/syntheseModule/services/store.service.ts, frontend/src/app/syntheseModule/synthese-results/synthese-list/modal-download/modal-download.component.ts, frontend/src/app/syntheseModule/synthese.component.html, frontend/src/app/syntheseModule/synthese.component.scss, frontend/src/app/syntheseModule/synthese.component.ts
Code refactoring and improvements.
Move search bar toggle button in the middle of page height (like Validation, and more visible).
=> Refactor Synthese: improve data loading and parsing

backend/geonature/core/gn_synthese/blueprints/exports.py
=> [Synthese] Fix export for sensitive observations

contrib/occtax/frontend/app/occtax-form/releve/releve.component.html
=> fix(occtax/releve): fix routerlink when cancelling edition in duplicate module

frontend/src/app/syntheseModule/taxon-sheet/tab-observations/tab-observations.component.ts
=> feat(taxon-sheet): redirection from obs in taxon sheet to the detail page in the synthese

backend/geonature/migrations/versions/ab7d63977c5d_increase_the_length_of_a_datasets_label.py
=> feat(metadata): increase size of the dataset name string

frontend/package.json, frontend/src/app/GN2CommonModule/form/individuals/individuals.component.ts, frontend/src/app/GN2CommonModule/form/media/medias.component.ts, frontend/src/app/GN2CommonModule/form/synthese-form/synthese-data.service.ts, frontend/src/app/app.module.ts, frontend/src/app/components/home-content/home-discussions/home-discussions.service.ts, frontend/src/app/components/home-content/home-validations/home-validations.service.ts, frontend/src/app/components/nav-home/nav-home.component.ts, frontend/src/app/metadataModule/metadata-dataset.component.ts, frontend/src/app/metadataModule/services/metadata.service.ts, frontend/src/app/routing/routing.service.ts, frontend/src/app/syntheseModule/taxon-sheet/infos/taxonomy/taxonomy.component.ts, frontend/src/app/syntheseModule/taxon-sheet/tab-media/tab-media.component.ts, frontend/src/app/syntheseModule/taxon-sheet/taxon-sheet.route.service.ts, frontend/src/app/userModule/user.module.ts
Found by @marcantoinedupre 
closes #3700
=> fix(lint): prettier check (re)include typescript files

docs/admin-manual.rst, docs/sensitivity.rst, install/03b_populate_db.sh
https://github.com/PnX-SI/GeoNature/issues/3680
=> Update ref to 18

backend/geonature/core/imports/checks/dataframe/cast.py, backend/geonature/core/imports/checks/sql/utils.py, backend/geonature/migrations/versions/8c31693c2183_import_review_on_error_types_description.py
This PR propose to improve the error description message.
=> feat(import) : Improve error import description
